.editorconfig, .gitignore, .travis.yml, karma-tests/Makefile, karma-tests/karma.conf.js, karma-tests/wombat.spec.js, package.json
Replacement for #149 into separate branch
=> Wombatjs tests

appveyor.yml, extra_requirements.txt, pywb/apps/frontendapp.py, pywb/recorder/multifilewarcwriter.py, pywb/recorder/test/test_recorder.py, pywb/rewrite/templateview.py, pywb/warcserver/index/aggregator.py, pywb/warcserver/index/test/test_dir_agg.py, pywb/warcserver/index/test/test_memento_agg.py, pywb/warcserver/index/test/test_timeouts.py, pywb/warcserver/index/zipnum.py, tests/test_auto_colls.py
pywb builds on windows, CI running with Appveyor
=> Windows Build Fixes/Appveyor CI

pywb/apps/frontendapp.py, pywb/apps/rewriterapp.py, pywb/utils/memento.py, pywb/warcserver/handlers.py, tests/memento_fixture.py, tests/test_memento.py
Add timemap support, ensure compatibility with 200-style negotiation.
=> Readd Memento (Pattern 2.2) Support

pywb/rewrite/content_rewriter.py, pywb/rewrite/default_rewriter.py, pywb/rewrite/html_rewriter.py, pywb/rewrite/regex_rewriters.py, pywb/rewrite/test/test_content_rewriter.py, pywb/rewrite/test/test_header_rewriter.py, pywb/rewrite/test/test_html_rewriter.py, pywb/rewrite/test/test_regex_rewriters.py, pywb/static/wombat.js
- Improve content type resolution in ContentRewriter
- JS Obj Proxy Rewriter: preserve whitespace
- Account for relative urls when checking allowed urls for history
=> More Rewriting Improvements

pywb/apps/cli.py, pywb/apps/frontendapp.py, pywb/manager/autoindex.py, pywb/manager/manager.py, pywb/warcserver/resource/responseloader.py, pywb/warcserver/test/testutils.py, pywb/warcserver/warcserver.py, tests/base_config_test.py, tests/config_test_record.yaml, tests/test_auto_colls.py, tests/test_record_replay.py
Add support for basic recording via `recorder: <coll>` config setting
=> Recorder App Support

pywb/rewrite/regex_rewriters.py, pywb/rewrite/test/test_regex_rewriters.py
Rewrite "return this" for proxy obj
=> Better "return this" rewrite

pywb/static/wb_frame.js, pywb/templates/frame_insert.html
- Remove window.location.hash from url construction, include when instantiating
- Bind event callbacks
- Add `load_url` function to update iframe src
- Add `close` function to remove event binding
=> Updates	to wb_frame.js

pywb/apps/cli.py, pywb/apps/rewriterapp.py, pywb/recorder/filters.py, pywb/recorder/test/test_recorder.py, pywb/rewrite/templateview.py, pywb/warcserver/resource/responseloader.py, pywb/warcserver/test/test_handlers.py, pywb/warcserver/test/test_upstream.py, setup.py
- webagg->warcserver
- setup.py: packages and entry points
- templateview param: 'webrec.template_params' -> 'pywb.template_params'
=> Renaming Pass: Webagg -> Warcserver

Dockerfile, appveyor.yml, extra_requirements.txt, pywb/apps/frontendapp.py, pywb/utils/loaders.py, pywb/utils/test/test_loaders.py, pywb/warcserver/handlers.py, pywb/warcserver/index/aggregator.py, pywb/warcserver/index/query.py, pywb/warcserver/index/test/test_zipnum.py, pywb/warcserver/index/zipnum.py, pywb/warcserver/warcserver.py, tests/test_auto_zipnum_dir.py, tests/test_zipnum_auto_dir.py
- update s3 to use boto3
- ensure zipnum indexes (.idx, .summary) are picked up automatically via DirectoryAggregator
- ensure showNumPages query always return a json object, ignoring output=
- add tests for auto-configured zipnum indexes
=> s3 and zipnum fixes:

CHANGES.rst, README.rst, docs/index.rst, docs/manual/apis.rst, docs/manual/configuring.rst, docs/manual/memento.rst, docs/manual/rewriter.rst, pywb/__init__.py
* Add Docs for Memento API, Rewriter, and compatibility sections
* Bump version to 2.0.0, fix README
=> Docs Update for 2.0

pywb/static/query.js, pywb/templates/query.html, setup.py, tests/test_integration.py
- Add new static files to package
- Fix 0 results display
- Fix wording to "captures"
=> Fix Query UI

pywb/manager/manager.py
python3: `raw_input()` was renamed to `input()`
=> make manager commands working with python3

.coveragerc, .travis.yml, README.rst, appveyor.yml
- Switch to codecov for coverage
- Update README badges
=> Update coverage reporting

Dockerfile, README.rst, docs/manual/cdxserver_api.rst, docs/manual/configuring.rst, docs/manual/memento.rst, docs/manual/recorder.rst, docs/manual/rewriter.rst, docs/manual/usage.rst, docs/manual/warcserver.rst, pywb/static/default_banner.js, pywb/static/vidrw.js, pywb/static/wb_frame.js, pywb/static/wombat.js
- Update text and fix spelling errors in docs and README
- Update Dockerfile to remove deprecated field, add support for custom base image
=> Text tweaks/Dockerfile update

pywb/rewrite/rewrite_amf.py
Small bug introduced by commit #d8b6731
=> rewrite_amf.py: Fix bug introduced by recent refactoring

pywb/static/wombat.js
URLs requiring change: https://www.facebook.com/
**Replaces 1/2 of PR #349**
Facebook polyfills both `requestAnimationFrame` and `cancelAnimationFrame`, when we return the polyfill functions bound to window they can detect that and complain. 
The fix is to not return a bound function when `prop` is `requestAnimationFrame` or `cancelAnimationFrame` **IFF** Function.toString does not return `"native code"`
- if prop is requestAnimationFrame (raf) or cancelAnimationFrame and it was polyfilled by FB do not bind
=> wombat.js: default_proxy_get improvement Facebook fix

CHANGES.rst, docs/manual/configuring.rst, docs/manual/memento.rst, requirements.txt
- Update CHANGES.rst for 2.0.4
- Docs: Improve new proxy docs for (#316), fix URL-T->URI-T
- Requirements: bump to wsgiprox>=1.5.1
=> text updates:

pywb/static/default_banner.js, pywb/static/wb_frame.js, pywb/static/wombat.js
Additional updates to favicon changes from #356. Favicon and title setting moved to default_banner.js from wb_frame.js to allow for easier overriding/customization.
=> Favicon work

pywb/static/wombat.js
wombat.js:
- Added override for setTimeout and setInterval because [setTimeout|set…Interval]('document.location.href = "xyz.com"', time) is legal and used
- Added override for window.origin (https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/origin) available in Chrome 59+ and FF 54+
URL for `setTimeout` and `setInterval`: https://guides.library.upenn.edu/c.php?g=870924
- Site tracks link clicks and defers browser navigation by doing `setTimeout('document.location.href = "xyz.com"', time)` once they have done their tracking work
=> Add setTimeout, setInterval, and window.origin overrides to wombat.js

.travis.yml, pywb/apps/cli.py, pywb/apps/frontendapp.py, pywb/apps/rewriterapp.py, pywb/apps/test/test_wbrequestresponse.py, pywb/apps/wbrequestresponse.py, pywb/rewrite/templateview.py, pywb/static/autoFetchWorker.js, pywb/static/autoFetchWorkerProxyMode.js, pywb/static/wombat.js, pywb/static/wombatProxyMode.js, pywb/templates/head_insert.html, setup.py, tests/test_auto_colls.py, tests/test_cli.py, tests/test_proxy.py
Implemented preservation worker for proxy mode:
- Split wombat and preservation worker into two files (proxy mode and non-proxy mode)
- Started root config file control over including wombat and preservation worker in proxy or non-proxy mode
- Added additional proxy mode + preservation worker only route for fetching the preservation worker code nicely for CORS
- head_insert.html: only include wombat in proxy mode when env.pywb_proxy_magic exists and wombat_mode states we should include it
- templateview.py: when in proxy mode HeadInsertView.create_insert_function calculates the wombat_mode proxy mode is operating in, `w = use wombat`, `p = use preservation worker` and an empty string means do not use either.
- wombatProxyMode.js: preservation worker is used when wbinfo.wombat_mode …
=> Preservation Worker Proxy Mode 

pywb/static/wombat.js
Added window.Text override to wombat.js to account for css in JS frameworks that like to append a single text node as a child to a style
node modifying and then only modify that text node to add/remove css dynamically via:
- initTextNodeOverrides (entry point)
- overrideTextProtoFunction (overrides the appendData, insertData, and replaceData functions of inherited by Text)
- overrideTextProtoGetSet (overrides property getters and setters of data and wholeText)
Added window.CSSStyleSheet.insertRule override
- dynamically adds a raw css rule (text) to an existing stylesheet
URLs requiring the change:
- insertRule: https://www.fulcrum.org/epubs/4t64gn875?locale=en#/6/2[Cover]!/4/1:0
- initTextNodeOverrides: https://jijkiest.vrtnws.be/
=> Add text node and CSSStyleSheet.insertRule overrides for improved replay fidelity of CSS in JS framework handling  

CHANGES.rst
Started initial pywb 2.0.5 changelist
=> [WIP] pywb 2.0.5 changelist

README.rst, pywb/apps/cli.py, tests/test_cli.py
Update README to 2.1
Fix typo in enable-auto-fetch, add test
=> README: update 2.0 -> 2.1

pywb/static/autoFetchWorker.js, pywb/static/wombat.js
autoFetchWorker.js:
- ensured that autoFetchWorker uses full srcset URLs
- resolves the URL against the img.src or document.baseURI if not rewritten
- otherwise ensures the rewritten URL is not relative or schemeless
wombat.js:
- AutoFetchWorker updated extractFromLocalDoc to send URL resolution information to the worker
- defer extractFromLocalDoc and preserveSrcset postMessages to ensure page viewer can see the images first
URL requiring change: https://webkit.org/demos/srcset/
=> Ensure Auto Fetch Worker can correctly resolve srcset URLs if not rewritten 

pywb/static/wombat.js
improved the rewrite_html_full check in wombat:
- FullHTMLRegex: performs a case insensitive check for <html, <body, <head and <!doctype html>
updated rewrite_elem to:
- rewrite meta tags that delievered csp policies
- check for additional attributes that could contain un-rewritten URLs (form.style, iframe.style, img.style)
`iframe.srcdoc = "string of html"` is becoming a more popular means of getting content into the dom as well as the usual suspects (document.write|writeln, .inner/outterHTML).
The `srcdoc = "string of html"` use case may include a full document i.e `<!doctype...` the previous check did not include this and was not case insensitive which 
allowed full strings of (html, head, body) html to fall through to non rewrite full (not desired).
Similarly including a metatag with …
=> wombat improved rewrite_html_full check and rewrite_elem improvements 

CHANGES.rst
=> updated Changes.rst to include PRs #395, #397, #398

pywb/static/wombat.js, pywb/static/ww_rw.js
Improved rewriting URLs within web workers by including the full URL the worker came from by including the absolute URL (when applicable) of the original worker URL.
Fixes #419
=> Improved web worker URL rewriting  

pywb/static/autoFetchWorkerProxyMode.js, pywb/static/wombatProxyMode.js
Added methods to AutoFetchWorker in proxy mode that allow external JS to initiate checks
Updated the actual proxy mode worker implementation to match the functionality added
=> Exposed AutoFetchWorker on window in proxy-mode

.travis.yml, .travis/install.sh, .travis/test.sh
update pip and setuptools when running install.sh found in .travis
use xenial distrubtion
only run webrecorder-tests using pywbtest and chrometest marker expression
=> Fix ci usage of wr-tests 

.travis.yml
Added xvfb to services due to travis changes on xenial
=> (WIP) Ensure XVFB works

pywb/rules.yaml
Updated rules for facebook timeline capture/replay.
=> rules: add new fb rule for pages

.travis.yml, pywb/recorder/recorderapp.py, pywb/rewrite/content_rewriter.py, pywb/rewrite/html_rewriter.py, pywb/rewrite/test/test_html_rewriter.py
Improvements for edge-case HTML rewriting
- If HTML content starts with `[UTF-8 BOM]<!DOCTYPE html>`, ensure still detected as HTML
- Ensure incorrect IE conditionals declarations, eg. `<![endif]-->` considered a closing marker, fixing #425
- Recorder: Ensure `Transfer-Encoding` never set as part of recorder WSGI response
=> Edge-case and HTML Rewrite Fixes

docs/manual/usage.rst
Fixes #299 
Document improved Docker config from #446
=> Add Docker info to Docs

CHANGES.rst
Started the pywb 2.2.0 changelist
=> pywb 2.2.0 changelist

pywb/static/query.js
Reworked how we construct the query to better differentiate between coming from the collection search interface vs direct querying
This was accomplished by simplifying how the CDX query is built
- strip our prefix from our locations URL 
- if the query came from a collections search page `/*?url=` and if so build query using its information
- otherwise check to see if we are displaying an direct query: `/*/url`, `/fromDT/url`, or `/fromDT-toDT/url` 
Note the file was reformatted to fit the code style of the upcoming wombat overhaul PR
fixes #455
=> Query UI: better differentiation between prefix/*?url and prefix/*/url

pywb/apps/rewriterapp.py, pywb/apps/wbrequestresponse.py, pywb/recorder/multifilewarcwriter.py, pywb/recorder/recorderapp.py, pywb/rewrite/content_rewriter.py, pywb/utils/geventserver.py, pywb/utils/io.py, pywb/utils/loaders.py, pywb/warcserver/index/indexsource.py, pywb/warcserver/index/zipnum.py, pywb/warcserver/resource/resolvingloader.py, pywb/warcserver/resource/responseloader.py, requirements.txt
improved pywb's closing of open file handles and http connects by add…ing to pywb.util.io three additional methods that do not raise
- close_raw: handles closing of the raw property
- full_close: fully closes a stream
- close_fh: close a file handle
used the three new closing methods throughout pywb
reformatted and optimizes import of files that were modified
=> Improved handling of open http connections and file handles

pywb/utils/loaders.py
Specified the loader to be use in `yaml.load` as not specifying it is now deprecated
Fixes #465
=> No longer use deprecated yaml load

pywb/warcserver/resource/resolvingloader.py, tests/test_redirects.py
If a revisit record has the empty digest, don't attempt to lookup the original!
Fix for ukwa/ukwa-pywb#53
=> Revisit Lookup Fix for Empty Records

pywb/static/default_banner.css, pywb/static/default_banner.js, pywb/templates/banner.html, pywb/version.py
Fix Banner not showing up in non-framed replay or proxy mode.
Bump version to RC 4
=> Banner fix

requirements.txt
Upgrade gevent to 20.9.0. The current version is outdated and results in the app not starting as documented in #580
=> upgrade gevent to 20.9.0

.github/workflows/ci.yaml, pywb/warcserver/index/test/test_cdxops.py, tests/test_proxy.py, tox.ini
Use GH actions for CI since Travis is now more limited.
=> Use Github Actions for CI

pywb/rules.yaml
Updates `rules.yaml` with additional rules necessary for replaying youtube and vimeo captures.
=> Rewriting Rules Update

pywb/warcserver/warcserver.py, tests/config_test_record_dedup.yaml, tests/test_record_dedup.py, tests/test_record_replay.py
Add tests for new dedup system added in #611
=> Dedup Test

pywb/rules.yaml
More general fix for youtube no-dash rewriting.
=> yt rules: more general yt rules

CHANGES.rst, config.yaml, docs/manual/access-control.rst, docs/manual/localization.rst, pywb/manager/locmanager.py, pywb/rewrite/templateview.py, pywb/templates/base.html, pywb/templates/error.html, pywb/templates/frame_insert.html, pywb/templates/head_insert.html, pywb/templates/header.html, pywb/templates/index.html, pywb/version.py, setup.py, tests/test_auto_colls.py
- add missing header.html
- docs: support 'i18n' extra, mention in docs
- use 'default_locale' for html lang tag
- access control docs: fix documentation for adding user with acl command
- bump version to 2.6.0b1
=> Localization / doc fixes

CHANGES.rst, extra_requirements.txt, pywb/apps/rewriterapp.py, pywb/manager/manager.py, pywb/rewrite/templateview.py, pywb/templates/header.html, requirements.txt, setup.py
- fix running wb-manager w/o i18n dependencies
- dependencies: move babel to extra_requires, show warning if locale used or 'wb-manager i18n' called and i18n are not installed
- not found page: don't language switch header banner on nested content frame
=> more locale fixes:

CHANGES.rst, config.yaml, pywb/apps/cli.py, pywb/manager/manager.py, pywb/rewrite/templateview.py, pywb/version.py
version display: add -V/--version flag to wb-manager and wayback/pywb commands to display version and exit
update CHANGES
comment out default locales in config.yaml
only show warning for needing to installing i18n extra when locales actually specified in config
bump to 2.6.0b3
=> Add Version Display + Fix Warning

pywb/warcserver/index/indexsource.py
URL is not properly encoded in request to warcserver.
Fixes #658.
Not sure if this is a breaking change or the proper way to fix this.
=> Encode load url properly

pywb/rules.yaml
=> Rules Update: Add rewrite rule for disable dash for IG

pywb/apps/frontendapp.py, pywb/apps/rewriterapp.py, pywb/version.py, tests/test_integration.py
Ensure the `pywb.app_path`, `pywb.host_path` and `pywb.static_path` are set for all templates, including replay
and non-replay templates.
Also ensure the X-Forwarded-Proto is accounted for.
Update to latest wombat (3.3.6)
bump version to 2.6.3
Fixes #686 , regression is 2.6.2
=> More consistent env var setting / static path fix

.github/workflows/release.yaml, CHANGES.rst, pywb/rewrite/regex_rewriters.py, pywb/rewrite/test/test_html_rewriter.py, pywb/rewrite/test/test_regex_rewriters.py
Fix for #684 + 2.6.3 CHANGELIST + new CI release
=> Misc fixes for 2.6.3

pywb/apps/rewriterapp.py
This one part seems not to cope when SCRIPT_NAME is not defined.
Default to `''` like everywhere else in the code.
=> Cope when SCRIPT_NAME is not defined

requirements.txt
Fixes https://github.com/webrecorder/pywb/issues/704
=> Pin werkzeug version to 1.0.1. Fix #704

CHANGES.rst, pywb/rewrite/regex_rewriters.py, pywb/rewrite/test/test_regex_rewriters.py, pywb/version.py, pywb/warcserver/inputrequest.py, requirements.txt
pywb 2.6.7 bugfix release
- Fix edge-case eval rewriting
- bump gevent to latest (21.12.0)
- remove extraneous print
=> pywb 2.6.7

docs/manual/usage.rst
This PR adds information to the Usage docs recommending that uwsgi and its dependencies are resolved in a virtual environment.
Resolves https://github.com/webrecorder/pywb/issues/769
Built section (without live docs style):
=> Add uwsgi virtualenv information

pywb/apps/static_handler.py
Changes StaticHandler to refuse to serve static files outside of static_dir.
Prevents the path traversal attack reported in #931.
=> Refuse to serve static files that are outside of static_dir
