webrecorder/pywb

pywb/static/wombat.js

Fix typo in handling of no_rewrite_prefixes

---

README.rst

Without this additional command, the subsequent commands won't run for the naive user.

Added change directory command to samples and tests

---

pywb/rewrite/rewrite_content.py
setup.py

Here's a basic implementation of using python-webencodings to handle character encoding.
This correctly causes the head insert to be added to http://www.geocities.jp/koreanlaws/yousiengumi.html using shift_jis encoding instead of falling back on utf-8. (I confirmed this via print statements.)
I've thought of two cases where this might actually matter:
- If the collection name or some other part of wbinfo has unicode characters. (Probably a good idea in general to support foreign-language collection names, right?)
- If the page is in some non-utf8-compatible encoding (utf16? others?) set via response headers.
... but I confess I haven't actually tested either of those.

Use webencodings to encode head_insert_str.

---

pywb/static/wombat.js

In Safari 9, Object.getOwnPropertyDescriptor(domObject.prototype, prop)
returns descriptors which have the correct structure but undefined
getters and are marked as unconfigurable.
See https://bugs.webkit.org/show_bug.cgi?id=49739#c19
for details. The getters cannot be retrieved via obj.__lookupGetter__()
either.
* Resolve the issue by skipping overrides for DOM properties
where the property is not configurable, or the original getter for
a property could not be retrieved.
* Lookup the 'baseURI' property on the correct prototype (Node,
not document)
This fix also resolves the problem where accesses to document.baseURI
on Edge would fail.

Fix Wombat in Safari 9

---

pywb/static/wombat.js

Fix regression in baseURI override, spotted by the Karma
tests.
The getter should be looked up on Node.prototype, not Node.

Lookup baseURI getter on Node.prototype, not Node

---

.travis.yml
karma-tests/karma.conf.js
karma-tests/wombat.spec.js
pywb/static/wombat.js

(This PR also includes https://github.com/ikreymer/pywb/pull/154, which is necessary for the tests to pass)
* Provide a fallback mode in the Karma tests which tests
against a local browser (defaults to Firefox) if Sauce Labs
credentials are not set.
This is useful for local testing for contributors who
might not have a Sauce Labs account.
* Add Safari under OS X to the set of Sauce Labs browsers
that the Karma tests are run against, following the merge
of the WombatJS fixes for Safari and Edge.
Although Edge now works under manual testing, automated testing against Edge via Sauce Labs is not yet working for reasons yet to be determined.

Enable testing against Safari on Sauce Labs.

---

.travis.yml
karma-tests/dummy.html
karma-tests/karma.conf.js
karma-tests/wombat.spec.js
pywb/static/wombat.js

(Note: This PR also includes the changes from #156 and #154 , I can either rebase once they are merged or we can just merge this one).
This adds Microsoft Edge to the Sauce Labs test configuration in Karma, fixes a couple of quirks with how the tests run (eg. Edge did not load JS code in an <iframe> if the iframe's main URL failed to load, whereas the other browsers did) and also corrects the object that the baseURI override is installed onto.
When using a version of pywb with these combined fixes, Via works against Edge and Safari.
Fixes #148

Microsoft Edge compatibility fixes

---

pywb/rewrite/html_rewriter.py
pywb/rewrite/test/test_html_rewriter.py

For Via, we want rel=canonical links to resolve to the same
absolute URL as it did on the original page.
For absolute URLs, no rewriting is necessary. If the original
rel=canonical URL was relative however, it needs to be resolved
relative to the original URL.
See https://github.com/hypothesis/via/issues/65 for context.

Resolve relative canonical paths if rewriting is disabled

---

karma-tests/wombat.spec.js
pywb/static/wombat.js

The values returned by getting the 'href' and 'toString'
properties of an anchor element should be the same.
This inconsistency broke the URL polyfill in
https://github.com/inexorabletash/polyfill under Microsoft Edge
This was the underlying cause of the issue seen in https://github.com/hypothesis/via/issues/64

Override HTMLAnchorElement.prototype.toString()

---

pywb/rewrite/html_rewriter.py
pywb/rewrite/test/test_html_rewriter.py

Strictly speaking a `srcset` attribute must consist of one or more
strings (http://w3c.github.io/html/semantics-embedded-content.html#element-attrdef-img-srcset).
However are websites out there that specify an empty string as the value.
This commit makes sure that the rewriting does not break and just returns an empty string.
An example is [this](https://gamesandlearning.wordpress.com/2016/02/19/playful-annotation-in-the-open/) which produces this HTML that breaks the current behaviour:
```html
```

Allow rewriting of empty srcset attributes

---

pywb/apps/cli.py

before:
```
$ wayback --help
usage: pywb Wayback Web Archive Replay [-h] [-p PORT] [-t THREADS] [-s SERVER] [-a] [-d DIRECTORY]
optional arguments:
-h, --help            show this help message and exit
-p PORT, --port PORT
-t THREADS, --threads THREADS
-s SERVER, --server SERVER
-a, --autoindex
-d DIRECTORY, --directory DIRECTORY
Specify root archive dir (default is current working directory)
```
after:
```
$ wayback --help
usage: wayback [-h] [-p PORT] [-t THREADS] [-s SERVER] [-a] [-d DIRECTORY]
pywb Wayback Web Archive Replay
optional arguments:
-h, --help            show this help message and exit
-p PORT, --port PORT
-t THREADS, --threads THREADS
-s SERVER, --server SERVER
-a, --autoindex
-d DIRECTORY, --directory DIRECTORY
Specify root archive dir (default is current working …
```

fix/tweak for cli --help

---

pywb/framework/wsgi_wrappers.py
pywb/utils/test/test_loaders.py

- check whether exception status conforms to the format expected by wsgi `NNN message`
- try to convert status if not
- make sure err_msg is of type str

Improve handling of exceptions in wsgi_wrappers, fixes #219

---

pywb/rewrite/content_rewriter.py
pywb/rewrite/default_rewriter.py
pywb/rewrite/regex_rewriters.py
pywb/rewrite/test/test_content_rewriter.py
pywb/rewrite/test/test_header_rewriter.py
pywb/rewrite/test/test_regex_rewriters.py
pywb/static/wombat.js

- Better handling of missing Content-Type
- Ensure correct content-type is used, ensure xhtml served as text/html
- Client Side JS Obj Proxy: Node.computeDocumentPosition() converts proxy->obj
- Server Side (JS Obj Proxy): rewrite `= this` assignment to check for proxy
- New tests for content rewriter, js obj proxy rewriter regex replacements

Rewrite Improvements

---

pywb/static/wombat.js

Custom LocalStorage/SessionStorage override:
- custom, in-mem only objects for localStorage and sessionStorage to avoid polluting browser storage, using Proxy if available to allow accessors
- storage event listeners tracked in addEventListener override, called directly with custom StorageEvent.
- storage event listener wrapped in SameOriginListener() to prevent notifying listeners from different origins
-addEventListener fix: prevents duplicate additions for wrapped listeners, for both message and storage

LocalStorage/SessionStorage Overrides

---

pywb/apps/frontendapp.py
pywb/apps/rewriterapp.py
pywb/warcserver/basewarcserver.py
pywb/warcserver/warcserver.py
tests/config_test_root_coll.yaml
tests/test_cdx_server_app.py
tests/test_integration.py
tests/test_root_coll.py

frontendapp/warcserver improvements:
- support '/cdx' endpoint for every collection, exposing standard cdx-server api
- remove '-cdx' endpoint in warcserver, redundant with index and frontend /cdx endpoint
- warcserver: simplify paths! support static paths (/A, /B) + dynamic paths (/<path>) on same endpoint

Support CDX-Server API

---

pywb/indexer/archiveindexer.py

Extract WARC field [WARC-Identified-Payload-Type](https://github.com/iipc/warc-specifications/blob/gh-pages/specifications/warc-format/warc-1.1/index.md#warc-identified-payload-type)" and add it as field "mime-detected" to index entry, cf. [commoncrawl/nutch#3](/commoncrawl/nutch/issues/3).

Index WARC-Identified-Payload-Type

---

pywb/cdx/cdxops.py
pywb/cdx/test/test_cdxops.py

(fixes #249)
- the operator `~` now triggers regex matches
- contains match is performed with specific operator (default)
An extended description of the [`filter` param](/ikreymer/pywb/wiki/CDX-Server-API#filter) with the PR applied:
The `filter` param can be specified multiple times to filter by specific fields in the cdx index. Field names correspond to the fields returned in the JSON output. Filters can be specified as follows:
* `...coll-cdx?url=example.com/*&filter==mime:text/html&filter=!=status:200`
Return captures from example.com/* where mime is text/html and http status is not 200.
* `...coll-cdx?url=example.com&matchType=domain&filter=~url:.*\.php$`
Return captures from the domain example.com which URL ends in `.php`.
The `!` modifier before `=status` indicates negation. The …

CDX-API "filter" param: swap operators for regex and contains match

---

config.yaml
docs/manual/configuring.rst
pywb/apps/rewriterapp.py
pywb/utils/memento.py
pywb/warcserver/index/aggregator.py
pywb/warcserver/index/test/test_fuzzymatcher.py
pywb/warcserver/resource/pathresolvers.py
pywb/warcserver/resource/test/test_pathresolvers.py
pywb/warcserver/test/test_handlers.py
tests/memento_fixture.py
tests/test_cdx_server_app.py
tests/test_memento.py
tests/test_proxy.py
tests/test_record_replay.py

- add new cdx 'source-coll' field, storing only the collection
- ensure rel="collection" property included in the TimeMap and Link header
- tests: update all tests to include the 'source-coll' property
- docs: add 'identifying collection' to all collection docs

include the collection in Memento Link outputs:

---

pywb/apps/rewriterapp.py
pywb/rewrite/templateview.py
pywb/templates/head_insert.html
tests/config_test_redirect_classic.yaml
tests/test_proxy.py
tests/test_redirect_classic.py

- add support for redirect to exact timestamp mode via 'redirect_to_exact: true' config setting
- tests: ensure memento headers added for redirect-to-exact
- memento: ensure Link header added for intermediate resources, check for 'enable_memento' before adding
- config: config passed to head_insert template as 'config'
- insert legacy 'vidrw.js' script if 'enable_flash_video_rewrite' config is set to true
- config: use_js_obj_proxy now defaults to true
- memento/tests: add proxy with custom accept-datetime test

support for 'classic' pywb features and misc improvements:

---

pywb/apps/rewriterapp.py
pywb/indexer/archiveindexer.py
pywb/warcserver/handlers.py
pywb/warcserver/inputrequest.py
pywb/warcserver/test/test_inputreq.py

- rename PostQueryExtractor to generic MethodQueryCanonicalizer, handles OPTIONS verb in addition to POST
- use more generic 'query' instead of 'post_query' for method-query canonicalization
- append '__pywb_method=options' to OPTIONS responses to distinguish from get in MethodQueryCanonicalizer

http OPTIONS and HEAD canonicalization:

---

pywb/static/wombat.js
pywb/static/ww_rw.js
pywb/templates/head_insert.html

- add 'ww_rw' for injecting into webworkers via importScript() added when loading web workers as blobs
- 'WB_wombat_location' override checks for defaultView more consistently if _WB_wombat_location
- custom overrides __WB_pmw, WB_wombat_frameElement just fail silently instead of raising exception on assignment

client-side rewrite: web worker and document access improvements

---

pywb/rewrite/content_rewriter.py
pywb/rewrite/regex_rewriters.py
pywb/rewrite/rewrite_dash.py
pywb/rewrite/test/test_content_rewriter.py
pywb/rules.yaml
pywb/static/wombat.js
pywb/utils/canonicalize.py
pywb/utils/loaders.py
pywb/warcserver/index/fuzzymatcher.py
pywb/warcserver/index/test/test_fuzzymatcher.py

- Fuzzy match work for FB
- Support for 'find_all' fuzzy match, using regex `findall` call
- Keep trailing '?' on prefix queries

Fuzzy Rewrite Improvements

---

pywb/apps/cli.py
pywb/rewrite/content_rewriter.py
pywb/rewrite/test/test_content_rewriter.py
pywb/rules.yaml

- new rules to disable dash/hls for vimeo
- apply 'js_regexs' on 'json' content, using 'js-proxy' rewriter

Rules Work (vimeo) and live_only flag

---

.dockerignore
pywb/apps/rewriterapp.py
pywb/utils/io.py
tests/test_integration.py
tests/test_range.py

- fully support range requests on frontend, if range request reaches pywb
- add OffsetLimitReader() to skip offset and limit read
- disbale rewriting for range requests
- serve 416 if range outside of content-length
- tests: add tests for range request handling
dockerignore: add collections/

range request fixes:

---

pywb/apps/frontendapp.py
pywb/manager/autoindex.py

I tried changing the `collections_root` directory and ran into a problem with the AutoIndexer — it looks like you might be hard coding to the `collections: collections`. Passing in `colls_dir` from FrontEndApp to AutoIndexer instead.

add - pass in colls_dir instead of hardcoding

---

pywb/rewrite/html_rewriter.py
pywb/rewrite/test/test_html_rewriter.py
pywb/static/wombat.js

Part 1: This PR offers a tiny tweak, the result of investigating why certain images at https://lil.law.harvard.edu, like the logo, aren't currently being captured/played back.
It turns out that websites using `srcset` to implement responsive images normally define a list of sources separated by [both commas and whitespace](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images). The whitespace is necessary since URLs can contain commas in the path section without being percent-encoded (see related issue https://github.com/ikreymer/pywb/issues/238). Without the whitespace, browsers will/may interpret the list of sources as one giant url. 
The LIL src html:
```
```
currently results in the rewritten html:
```
```
which results in the request (404 Not …

Separate rewritten srcset image urls; handle urls with commas

---

pywb/rewrite/html_rewriter.py
pywb/rewrite/test/test_html_rewriter.py

This PR provides the rewriting of meta tag delivered Content-Security-Policies.
The rewriting of the tag is handled like the integrity attribute.
Fixes #273

Disable meta tag delivered Content-Security-Policies

---

pywb/static/wombat.js

This PR improves wombats fetch override and fixes #275. 
Both WombatLocation and URL have the property href whose getter results in an unrewritten URL, likewise when these objects are coerced to a string or the toString method is called.
This is undesired behavior when using Pywb or Webrecorder.
The fix is simple, added an additional check if input is of type object and has an href property which is non-null.
If so rewrite input.href and reassign input to the rewritten URL.

Improve wombats fetch override

---

pywb/manager/manager.py

should fix the error when calling the cli with no argument https://bugs.python.org/issue16308 
```
~ wb-manager
Error: 'Namespace' object has no attribute 'func'
```

wb-manager cli, fix for no arguments

---

appveyor.yml
docs/manual/configuring.rst
extra_requirements.txt
pywb/warcserver/http.py
pywb/warcserver/resource/responseloader.py
tests/test_socks.py

Add support for SOCKS proxy, enabled by setting `SOCKS_HOST` env var.
Mention SOCKS proxy support in Docs

SOCKS proxy

---

pywb/utils/format.py
pywb/warcserver/basewarcserver.py
pywb/warcserver/index/fuzzymatcher.py
pywb/warcserver/index/query.py
pywb/warcserver/index/test/test_fuzzymatcher.py
tests/test_cdx_server_app.py

- pywb.utils.format: add query_to_dict() to convert query string with support for list for certain params
- support multiple values for 'filter' cdx server param (fixes #284)
- pywb.utils.format: add to_bool() to convert string/int to bool (eg. for query args)
- fuzzymatch: add 'allowFuzzy' (default to true) to allow disabling fuzzy matcher
- tests: fuzzymather: test disabling fuzzy matcher with allowFuzzy=0
- tests: cdx-server api: add multiple filter tests, with and without fuzzy matching

warcserver/cdx query: filter improvements

---

docs/manual/configuring.rst
docs/manual/usage.rst
pywb/static/default_banner.js
pywb/templates/head_insert.html
tests/test_integration.py
tests/test_proxy.py

- don't include wombat.js in banner only mode, including in proxy mode
(instead, do set devicePixelRatio to fix certain fidelity issues)
- default_banner: set title to document.title on load when frameless, including in proxy mode
- improve docs for configuring proxy mode cert
- tests: update tests to ensure no wombat.js injected in proxy or banner-only mode

proxy-mode tweaks: (fixes #302):

---

docs/manual/configuring.rst
pywb/apps/frontendapp.py
pywb/templates/banner.html
tests/test_proxy.py

Allow disabling default banner insert and all head insert into replay when in proxy mode via
`use_banner: false` and `use_head_insert: false` options, respectively. Addresses #316

Proxy Options

---

pywb/static/wombat.js

This PR fixes #324 by check for the variadic case in the document.[write, writeln] function overrides.   
For reference consider the [Document IDL](https://html.spec.whatwg.org/multipage/dom.html#the-document-object)  excerpt below
```webidl
[OverrideBuiltins]
partial interface Document {
[CEReactions] void write(DOMString... text);
[CEReactions] void writeln(DOMString... text);
}
```
The changes made by this PR can be summarized as:
1. Added a reference to `$wbwindow.Function.prototype.apply` called `origFunctionApply` to account for the Function.apply override
2. Made the argument string (from the original override) a function variable 
3. If the length of the `arguments` object is less than or equal to 1, set string to `arguments[0]`
4. Otherwise convert the `arguments` object to an …

Fix wombats overrides of document.[write, writeln] to account for the variadic case

---

pywb/static/wombat.js

- if targetOrigin is the replay host, default to unrewritten from origin, not '*'
- don't set targetOrigin to 'null' or empty to avoid errors
- if target window's unrewritten origin is actually 'null' or '', don't pass message at all, and don't set to '*' -- represents actual behavior,
as postMessage to 'null' origin (about:blank page) will be received only if targetOrigin is already '*'.
Fixes some subtle behavior related to postMessage override when calling postMessage on an about:blank window. Avoid setting targetOrigin to `*` or to `"null"` or `""` empty origin. Don't send message at all if ending up empty or null origin.

postMessage edge cases fixes: safer postmessage:

---

extra_requirements.txt
pywb/rewrite/rewrite_amf.py
pywb/warcserver/amf.py
pywb/warcserver/inputrequest.py
pywb/warcserver/test/test_amf.py
pywb/warcserver/test/test_inputreq.py
requirements.txt
setup.py

The current version of `pywb` have some problems with `AMF`:
- It was developed to only support `AMF` messages from `Adobe Flex` (`Adobe Flex` is a Flash framework)
- The body of a request can be JSON, and the order of attribute can be a problem.
Here, we have developed a small class that gives a string representation of an `AMF` request. It supports pure `AMF` and `Flex` messages and tries to reorder the attributes of JSON objects.
Here are some pure `AMF` websites:
1.  [**matribu**](http://matribu.onf.ca/#/matribu)  -  [replay link](https://webrecorder.io/hhardy/amf/20180420140548$br:chrome:53/http://matribu.onf.ca/#/matribu) : With the patch, you will be able to record and replay the project.   
2.  **PIB** -  [replay link](https://webrecorder.io/hhardy/amf/http://pib.onf.ca/)To see …

Handle amf requests

---

pywb/rewrite/regex_rewriters.py
pywb/rewrite/test/test_regex_rewriters.py
pywb/static/wombat.js

- server-side: rewrite '}(this)' or '})(this)' with js object proxy override convert
- client-side: fix typo in 'onstorage' override, fix typo that prevented SameOriginListener() from being used -- ensure
custom 'onstorage' events only sent to original window

rewrite fixes (avoid infinite loops):

---

pywb/rewrite/html_rewriter.py
pywb/static/wombat.js

The `PRELOAD_TYPES` dictionary in `html_rewriter.py` was updated to include the `as` values: 
- `js_`: worker
- `oe_`: font, audio, video, embed, object, and track
This was done to in-order to ensure rewriting of all values listed in the [W3C Preload Spec](https://w3c.github.io/preload/).
Browser support [not behind flag](https://caniuse.com/#search=preload): Edge >= 17, Firefox >= 59, Chrome >= 50, Safari >= 11.1, Opera >= 37, and modern mobile browsers 
In order to support dynamic addition of `link` tags with `rel='preload'`, the `PRELOAD_TYPES` dictionary in `html_rewriter.py` was added to wombat as `linkAsTypes` object.
The `linkAsTypes` object in wombat also supports the rewriting of dynamic addition of `link` tags with `rel='import'` that contain the `as='x'` attribute. 
Browser …

Wombat rewrite improvements and updated server-side rewriting of link rel='preload'

---

pywb/rewrite/content_rewriter.py
pywb/rewrite/test/test_content_rewriter.py
pywb/rules.yaml

- treat as jsonp if url query contains 'callback=jsonp',
- fuzzy match query containing 'callback=jsonp'
- tests: add test for additional jsonp matching
Ex site for repro: https://www.ntr.nl/

jsonp rewriter: expand jsonp matching:

---

pywb/static/wombat.js

URL requiring change: http://qasrcc.org/events/calendar/
Renamed obj to this_obj to reflect that we using the deproxied this.
Use this_obj rather than window in the first if block that populates the from variable in order to match the logic in pm_origin and because proxy_to_obj returns raw this if not proxy.
These changes fix google calendar replay / recording.

Wombat postMessage improvements

---

pywb/rewrite/content_rewriter.py
pywb/rewrite/header_rewriter.py
pywb/rewrite/test/test_content_rewriter.py
pywb/static/wombat.js
pywb/templates/head_insert.html

Experimental SW rewriting fixes, attempts to address issues raised in #323:
- ServiceWorker override resolved to absolute url before rewriting to use the `sw_` modifier.
- `sw_` modifier is similar to `id_`, but adds `Service-Worker-Allowed` to domain root
- wombat: service worker override rewrites origin, setting a default origin to domain root with mp_ modifier (to match Service-Worker-Allowed header)
- wombat init: don't call wombat init_paths if wombat already inited, as may happen from imported document.

ServiceWorker Rewrite Improvements

---

pywb/static/wombat.js

Spec: https://drafts.csswg.org/css-font-loading/#FontFace-interface
Browser Support: Chrome + Android >= 35, FireFox + Android >= 41 
URL requiring change: [http://public.tableau.com/views/nationalwages21979-2017/Dashboard2](http://public.tableau.com/views/nationalwages21979-2017/Dashboard2?:embed=y&:showVizHome=no&:host_url=https%3A%2F%2Fpublic.tableau.com%2F&:embed_code_version=3&:tabs=no&:toolbar=yes&:animate_transition=yes&:display_static_image=no&:display_spinner=no&:display_overlay=yes&:display_count=yes&publish=yes&:loadOrderID=0&:increment_view_count=no)
Minimal Working Example: https://googlechrome.github.io/samples/font-face-set/
The `FontFace` override follows the override convent of the `Audio` override and the override can be summarized as:   
- If the source argument is not …

Added FontFace to wombat overrides

---

pywb/warcserver/resource/responseloader.py
tests/test_self_redirect.py

Update self-redirect handling to detect self-redirects when there are two continuous 3xx cdx entries, eg:
1) http://example.com/ -> https://example.com/ (301)
2) https://example.com/ -> https://www.example.com/ (301)
3) https://www.example.com/ (200)
Currently, this results in a redirect loop due to canonicalization of www. and https out of the urlkey.
Improves the self-redirect check to verify the urlkey of next url. If it matches the same as previous self-redirect, also reject as self-redirect.

Self-Redirect Fix

---

pywb/rewrite/html_rewriter.py
pywb/rewrite/test/test_html_rewriter.py
pywb/rewrite/test/test_url_rewriter.py
pywb/rewrite/url_rewriter.py
pywb/static/wombat.js

URL requiring change: http://fotopaulmartens.netcam.nl/vucht.php
Script tags with src='x' where x is not absolute, relative, schemeless, or contain `../` resolve (i.e. `js/scplayer.php?camera=paulmartens102129&server=6&port=443&protocol=https`) are resolved by the browser to include a non-js rewrite modifier.
While this is fine in most cases there exists cases where the server does not always send the correct JS MIME type causing JS to not be rewritten as JS. 
In this case PYWB will now turn the "super relative" URL into an absolute URL with the correct rewrite modifier (`js_`) and add an attribute, `__wb_orig_src` to the element containing the unrerwritten URL for wombat.
This case is detected by `html_rewriter.py` using the new method `_not_abs_rel_has_parentp` which contains some …

Server-side rewriting of script[src='js/...'] and link rel='import'

---

pywb/static/wombat.js

URL requiring change: http://fotopaulmartens.netcam.nl/vucht.php
Spec: https://www.w3.org/TR/SVG11/filters.html#FilterProperty
MDN Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/filter
The svg filter attribute is used to apply an `effect` to an element and has the value of `funciri | none | inherit` where `funciri = Functional notation for an IRI: "url(" <IRI> ")".`
There are some cases when the value is an `funciri` that is full URI (i.e `http://example.com#a1`) and in this case will cause a CSP violation (`Refused to frame`).
The rewriting of this attribute is handled in `rewrite_elem` via `rewrite_attr` and can be summarized as:
- if the element in question is an instance of `SVGElement` and has the `filter` attribute
1. rewrite using `rewrite_attr` using …

Add rewriting of SVG Filter attribute

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/replay_issue.md
.github/PULL_REQUEST_TEMPLATE.md
pywb/__init__.py

This PR adds github issue and pr templates in order to help streamline the creation of both issues and pull requests.
When a user goes to open a new issue for this project they will have the choice to select from three templates or use the default blank slate issue. 
Designed for quick identification of the information pertaining to the particulars of the PR

Add issue and pull request templates

---

.travis.yml
.travis/install.sh
.travis/test.sh

This pr is to include the replay tests provided by [webrecorder-tests](https://github.com/webrecorder/webrecorder-tests/tree/develop) into pywb's ci workflow.
The `.travis.yml` file was updated to include a matrix based off the `WR_TEST` environment variable set to true and false.
The build matrix excludes python 2.7 and 3.5 when `WR_TEST=true` because webrecorder-tests is python 3.6 based.
When python 3.6 and `WR_TEST=true` we use the apt addon `libnss3` to allow for browser based testing on the `trusty` linux distribution.
The two scripts in the .travis directory are to support the additional testing via webrecorder-tests.
The `install.sh` script contains the exact commands that were originally contained in the `install` field of `.travis.yml`. 
with the addition of the installation and …

Include pywb based webrecorder-tests to travis ci setup 

---

pywb/__init__.py
pywb/rewrite/regex_rewriters.py
pywb/rewrite/rewrite_dash.py
pywb/rewrite/test/test_content_rewriter.py
pywb/rewrite/test/test_html_rewriter.py
pywb/rewrite/test/test_regex_rewriters.py

- Split RxRewriter rules into separate class hierarchy, inited once
- Each RegexRewriter has a 'rules factory' which generates the rules for the rewriter
- If extra rules provided, recompile with dynamic rules, otherwise return existing fixed rules
- Avoids recompiling rules rx for each rewriter (unless dynamic rules used), instead store rules object per rewriter type

RegexRewriter Optimization

---

pywb/apps/cli.py

Added help messages to the `add_argument` method calls in class `BaseCli` where none were present yet. This documents the meaning and default values of the available CLI options.
It took me some time to find out e.g. the meaning and default value of the `--bind` option. Now a user won't have to search the docs or the source code for that.

Enhance help messages in the command line interface

---

pywb/rewrite/content_rewriter.py
pywb/rewrite/test/test_content_rewriter.py
pywb/static/wombat.js
pywb/static/ww_rw.js

**Replaces 1/2 of PR #349**
The spotify app and many other websites use `Web Workers (Worker)` that are created not using blobs; likewise with `ShardWorker`. 
The previous override only handled the blob case for `Worker` and thus any other use case was not handled properly.
The fix is to expand on the rewriting of worker urls for both `Worker` and `SharedWorker`. 
Includes a new override for `SharedWorker` and introduces a new modifier `wkr_`.
- improved worker rewriting: updated worker rewriting handles non-blob urls, added SharedWorker override
The min-rewriting system for workers was updated to provide a more complete system that now handles 
`importScripts`, `Worker.fetch`, and an `eval` edge case unique to the spotify app.   
- updated to be a much more complete rewriting system: …

Improved Web Worker and SharedWorker rewrite system

---

pywb/rules.yaml

Added facebook profile timeline fuzzy lookup rule to rules.yaml
The value of __adt is incremented to indicate position in timeline as shown below and the profile_id or pagelet_token contained in the data param identify the facebook user the timeline data is for
Covers both 
- https://www.facebook.com/ajax/pagelet/generic.php/ProfileTimelineProtilesPagelet
- https://www.facebook.com/ajax/pagelet/generic.php/ProfileTimelineProtilesPaginationPagelet

Facebook timeline fuzzy lookup rule

---

docs/manual/usage.rst

the error also has the side-effect that lines are not wrapped.

Fixes an enumeration issue in docs/usage.rst

---

pywb/static/wb_frame.js
pywb/static/wombat.js
pywb/templates/frame_insert.html

Favicon display in no-proxy mode with framed_replay: true.
When "iframe": "#replay_iframe", the icon of the tab in question is not visible (or a wrong icon is displayed provided from cache memory ) because of the presence of an added frame (#replay_iframe).
Indeed, the main frame can not get the right favicon in the presence of another sub frame (#replay_iframe).
The modifcation allows to get the replay_iframe favicon and apply it on the main frame to be correctly displayed in the tab.
( see Issue #342)

Page title and favicon display

---

karma-tests/wombat.spec.js
pywb/static/wombat.js
pywb/static/wombatPreservationWorker.js

This PR introduces to Pywb via changes to `wombat.js` and the addition of a new static resource `wombatPreservationWorker.js` the ability to preserve 
the set of values contained in the `srcset` attribute and images contained in `CSS media query rules`.
The preservation scheme is split into two parts:
1. `wombat`: Initiating `wombatPreservationWorker` and sending it `srcset` and `media query` values for preservation
2. `wombatPreservationWorker`: The [web worker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API) responsible for fetching the resources
In order to facilitate this new preservation scheme the changes to wombat are as follows. 
1. `WBPreserWorker`: a reference to the preservation worker abstraction used by wombat itself
2. `wbSheetMediaQChecker`: a reference to …

Advanced Srcset and Style Sheet Containing Media Queries Preservation

---

pywb/rewrite/content_rewriter.py
pywb/rewrite/test/test_content_rewriter.py

Add content sniffing to the html check of `_fill_text_type_and_charset` when the url ends with .json
The page https://032c.com/fred-turner-silicon-valley-thinks-politics-doesnt-exist, makes a request for some JSON at URL
https://032c.com/fred-turner-silicon-valley-thinks-politics-doesnt-exist.json
but the server sends it over as text/html.
Fixes: https://github.com/webrecorder/webrecorder-bug-reports/issues/1457

Ensure Pywb replays requests for JSON correctly when the original server who sent it said it was text/html   

---

pywb/indexer/cdxindexer.py
pywb/indexer/test/test_indexing.py

Added skipping of metadata records with mime = text/anvl to cdxindexer.py.
Older web archiving software, especially those that generate WARCS using the WARC/0.18 specification, use the mime type text/anvl 
for there metadata records. 
This can make replay of such pages (mime text/html, et al) that also have corresponding metadata records with mime text/anvl impossible.
Fixes https://github.com/webrecorder/webrecorderplayer-electron/issues/63.

Ensure WARC/0.18 metadata records with mime = text/anvl are not indexed for replay

---

docs/manual/configuring.rst
pywb/apps/frontendapp.py
tests/test_record_replay.py

When using an aggregate collection or sequential fallback collection as the source, this change allow recording to be limited to pages fetched from certain child collection.
The most probable use case is to limit recording to pages that are fetched from live but not from an existing collection. This can be accomplished by setting up an sequential fallback collection with an existing collection followed by live collection, then setting a recording filter.

Add recorder option to filter source collection

---

pywb/apps/frontendapp.py
pywb/apps/rewriterapp.py
pywb/rewrite/templateview.py
pywb/templates/banner.html
pywb/templates/frame_insert.html
pywb/templates/head_insert.html
pywb/templates/index.html
pywb/templates/query.html
tests/test_prefixed_deploy.py

Supports deploying pywb under a prefix on the web server, usually provided via WSGI `SCRIPT_NAME` field.
For example, deploying under `/prefix`, all collections would be accessed via
`/prefix/<coll name>/` and all static paths would be `/prefix/static/...`
Updates various jinja templates to use  `{{ static_prefix }}` to specify the correct static path.
(The `SCRIPT_NAME` field is modified internally as part of collection path lookup, so
saving original 'script name' in `pywb.app_prefix` WSGI env var).
Have several use cases, including UK Web Archive, Scalar prototype where pywb needs to be deployed under a prefix and not as root webapp.

Support non-root deployment of pywb

---

pywb/rewrite/content_rewriter.py
pywb/rewrite/html_rewriter.py
pywb/rewrite/test/test_content_rewriter.py

Additional fixes from bug introduced in #361, which could cause urls to be reencoded with the wrong encoding. The assumption was that all unicode urls will be %-encoded. However, if a url is not rewritten, such as an anchor, it would not be %-encoded.
Now checking if rewritten url is the same, and then returning the original value.
Also, optimizing for utf-8: if content known to be utf-8, use that encoding for decoding the stream for rewriting. Otherwise, default to decoding as latin-1 (ignore encoding), and re-encode only the urls as utf-8.

Encoding Fix

---

pywb/rewrite/content_rewriter.py
pywb/rewrite/test/test_content_rewriter.py

- if no encoding is detected, don't default to utf-8
- if no encoding known, encode banner as 'ascii' with 'xmlcharrefreplace', converting to xml entities
- tests: add tests for rewriting with no known encoding

encoding fix: additional fix to #376 for banner encoding:

---

pywb/static/wombat.js

Added check for rules to be null to the noop case in  deferredSheetExtraction (edge case)
Ensures that the CSS rule extraction from style tags checks both probably properties that the CSSRuleList can be on (cssRules or rules)
See https://www.youtube.com/ in FF.

Ensure that Preservation workers deferredSheetExtraction is guarded against null CSSRuleList

---

pywb/static/wombat.js
pywb/static/wombatProxyMode.js
pywb/templates/head_insert.html
tests/test_integration.py
tests/test_memento.py
tests/test_prefixed_deploy.py
tests/test_redirect_classic.py
tests/test_root_coll.py

In PR #339, removed the reinit of wombat that was caused by document import.
However, wombat reinit was originally added if the original init was 'synthetic' (from a call to init_new_window_wombat()) and needed to be reinited when the actual iframe content loads (e0878f0f670dfbe1f24ba0745a5b4b2fd2c85ac2)
This now always happens since the `frames` object wrapper inits all the iframes with init_new_window_wombat() 
This change allows the reinit of synthetic wombat, but not actual wombat loaded with the page.
A new flag `_wb_wombat.actual` is added in the init function.
The init logic has now also been moved to `_WBWombatInit` function in wombat.js and wombatProxyMode.js to avoid duplicating the logic in custom head inserts.
Also includes an optimization for `window.frames`. Since …

wombat reinit fix

---

pywb/static/wombat.js

Overrides `document.evaluate()` in a more generic way, also optimize the
override function to avoid modifying `arguments array` (as per https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#3-managing-arguments)
and call the original apply function to avoid redundant de-proxy checks.
Supercedes #384

wombat: argument de-proxy and optimization:

---

pywb/apps/rewriterapp.py
pywb/rewrite/cookie_rewriter.py
pywb/rewrite/test/test_content_rewriter.py
pywb/static/wombat.js
pywb/warcserver/resource/responseloader.py
tests/test_live_rewriter.py

This includes three rewriting fixes:
1) (Server-Side) Add cookies for all modifiers: when rewriting http-only cookies that have a path ending in `/` and 
added to an `mp_/` or `if_/` modifier, also add the cookie for all other common modifiers (`im_`, `js_`, `cs_`, `oe_`), as this cookie is likely a session cookie and other resources loaded with those modifiers may need the cookie as well. This solves the general issue of a cookie set on an `mp_` page not being accessible to css/js/other embeds. (Server-Side) 
2) If Content-Length header is of the form `Content-Length: num, num`, just use the first number. Occasionally seen if content-length is added twice somehow. (Server-Side)
3) Better relative url rewriting: When rewriting urls from `rewrite_elem()`, pass the element document to …

Rewriting fixes for http-only cookies, bad content-length, and document with base

---

CHANGES.rst
docs/manual/configuring.rst
pywb/__init__.py
pywb/apps/cli.py
pywb/apps/frontendapp.py
pywb/static/wombat.js
pywb/static/wombatProxyMode.js
pywb/templates/banner.html
pywb/templates/head_insert.html
requirements.txt
tests/config_test_root_coll.yaml
tests/test_cli.py
tests/test_integration.py
tests/test_proxy.py
tests/test_root_coll.py

Adds documentation for the auto-fetch system and makes the cli switches more consistent, with a few renames:
`use_banner` -> `enable_banner`
`use_head_insert` -> `enable_content_rewrite`
`use_wombat` -> `enable_wombat`
`use_auto_fetch_worker` -> `enable_auto_fetch`
The `enable_auto_fetch` switch is now global and applies to both proxy and url-rewriting modes.
Other cleanup: made gevent bounded in requirements.txt, bumped to 2.1.0 due to breaking changes with config option renames.
To cleanup the command-line options and add documentation for release!

Cleanup CLI Switches and Docs for Auto-Fetch System

---

pywb/apps/rewriterapp.py
tests/test_force_https.py

If the `X-Forwarded-Proto` header is set, override the existing scheme (specified via WSGI `wsgi.url_scheme`) with the value of the header.
As raised in #374, use this header instead of `force_scheme` config to allow specifying the scheme for url rewriting.
When running behind a reverse proxy, it is necessary to dynamically specify the scheme.
This allows more flexibility in specifying the scheme and avoiding the fixed config setting.
The `force_scheme` config is being deprecated.

Support X-Forwarded-Proto header to specify scheme

---

docs/manual/usage.rst

This patch updates the documentation to add a configuration snippet
for Apache.
This configuration can be used when launching `wayback` in the default
configuration, which is useful to add stuff like access control,
authentication, or encryption without going through the trouble of
setting up a UWSGI proxy.
The `force_scheme` configuration wouldn't be necessary if pywb would
support the (de-facto) standard `X-Forwarded-Proto` header. This is
not, unfortunately, currently the case so the configuration cannot be
only on Apache's side. Note that this is similar to the concerns raised in #314

add sample Apache configuration

---

pywb/rewrite/regex_rewriters.py
pywb/rewrite/test/test_regex_rewriters.py

Minor changes to regex to ensure `this.$location` is not treated same as `this.location`
`$location` was being rewritten incorrectly.
Fixes replay on React/Angular sites which use $location
Example: https://www.tajalindley.com/shop

Server-Side Rewrite: 'location' rewrite fix to avoid rewriting '$location'

---

karma-tests/wombat.spec.js
pywb/static/wombat.js

wombat `extract_orig()` incorrectly defaults to http when unrewriting scheme-relative urls.
This is incorrect and can cause subtle issues, when the scheme is later used, such as when replaying in proxy mode.
Proxy mode replay of content captured from https://frick.org/calendar
can fail due to http content requested from https, due to incorrect scheme used
during capture.

Use actual page scheme instead of defaulting to http when extracting original url

---

pywb/static/autoFetchWorker.js
pywb/static/autoFetchWorkerProxyMode.js
pywb/static/wombat.js
pywb/static/wombatProxyMode.js

Automatic fetching of picture > source[srcset] fixes #414
- added to the auto-fetch worker of both wombat and wombatProxymode
- added utility function isImageSrcset to wombat for determining if the srcset values being rewritten are from either a image tag or a source tag within a picture tag
- added utility function isImageDataSrcset to wombat to check for img/source data-srcset attributes
- reworked the backing auto-fetch worker to now queue all URLs and perform fetch batching with maximum batch size of 60. A delay of 2 seconds is applied after each batch.
Ensured that the srcset values sent to the auto-fetch worker can be resolved in non-proxy mode fixes #413
Renamed the auto-fetch class named used in proxy mode from AutoFetchWorker to AutoFetchWorkerProxyMode
Added checking of script …

Auto-Fetch: added picture > source[srcset] extraction and made non-proxy mode resolving of non-abs srcset URLs in the worker more robust  

---

pywb/rewrite/content_rewriter.py
pywb/rewrite/default_rewriter.py
pywb/rewrite/test/test_content_rewriter.py
pywb/rewrite/test/test_header_rewriter.py

Use same html-detection check as for text/plain before assuming content is html (similar to text/plain)
supersedes #426, fixes #424 
Occasionally binary content may be served with a mp_/ modifier as text/html. If so, it should not be treated as html and no rewriting should be attempted. Run the same html detection (check that file starts with an `<` char) as is used when modifier does not match expected mime type.
Avoid attempting to parse binary files as HTML.
FIxes #424 in more general way by ensuring fonts served via mp_/ are served underwritten binary regardless of modifier used.

Check text/html content to ensure actually html

---

pywb/static/autoFetchWorker.js
pywb/static/autoFetchWorkerProxyMode.js
pywb/static/wombat.js
pywb/static/wombatProxyMode.js

Added auto-fetching of audio and video resources in both proxy and non-proxy mode.
Renamed `isImageSrcset` to `isSavedSrcSrcset` and `isImageDataSrcset` to `isSavedDataSrcSrcset`
Because audio/video resources can be large the backing worker now has two queues that operate independently:
- 1st is for URLs for images (`queue`), limited to a maximum of 40 concurrent fetches 
- 2nd is for URL for audio/video (`avQueue`), limited to a maximum of 10 concurrent fetches
In non-proxy mode `AutoFetchWorker.extractFromLocalDoc` now performs work one JS eventloop tick after the documents ready state is complete.
In both proxy and non-proxy mode `AutoFetchWorker` uses a pre-computed selector that matches all the auto-fetch element and attribute combinations
- The resolution algorithm used by the …

Enabled auto-fetching of video, audio resources

---

pywb/static/default_banner.js
pywb/static/wb_frame.js

Ensured that the banner does not become stuck displaying "Loading..." on non-html content fixes #417
Introduced an optional relationship between ContentFrame and banners.
If a banner is exposed then ContentFrame controls the initialization of the banner and routes any messages received from the replay iframe to the banner.
When the replay iframe is navigated to a page and the replay iframe loads, the ContentFrame waits 2 seconds before checking to see if the banner still indicates it a loading state and if so updates the displayed information using the URL and timestamp the replay iframe was navigated to.
This change requires that all custom banners that wish to opt into this behavior 
- expose themselves on window as `WBBanner`
- implement an `init` function (create and display the …

Ensure banner does not get stuck displaying "Loading..." and introduce new banner behavior

---

pywb/recorder/recorderapp.py

Ensure RecorderApp proxy response does not add Transfer-Encoding header if one is set by Warcserver, as its added automatically via WSGI
Fixes #432, only occurs with python 2.7

Remove Transer-Encoding from internal response

---

pywb/rewrite/content_rewriter.py
pywb/rewrite/test/test_content_rewriter.py

Because the rewrite modifier `fr_` was not included in the acceptable modifiers for `guess-text` and `guess-html`, RewriteInfo believed that content under the `fr_` modifier was not to be rewritten.
Updated RewriteInfo._resolve_text_type to recognize the `fr_` rewrite modifier (indicates that the content is from a frameset's frame) as content to be rewritten
Added a test, test_rewrite_frameset_frame_content, to test_content_rewriter.py for these changes
URL requiring change: http://r-u-ins.link/

Ensured that the HTML content brought in via a frameset's frame is rewritten 

---

pywb/rewrite/rewriteinputreq.py
tests/test_record_replay.py

If `import brotli` fails, print warning and remove `br` from `Accept-Encoding`
Otherwise, can fail silently when trying to record/replay brotli content.
See #434

Brotli: Don't accept brotli if library can't be loaded.

---

pywb/rewrite/jsonp_rewriter.py
pywb/rewrite/test/test_content_rewriter.py
pywb/rewrite/test/test_jsonp_rewriter.py

JSONP Rewriter before only allowed matching function being matched, eg. `/* comment */ jQuery({`
Also support matching JSONP:
```
// Comment
jQuery({
```
as browsers also accept this as JSONP
Fixes replay issue in #459 
https://www.newblackmaninexile.net/

JSONP Rewriter: Fix regex to match both /* and // comments

---

pywb/warcserver/http.py

Added custom requests HTTPAdapter, PywbHttpAdapter, that restores the behavior of urllib3 < 1.25.x 
which was to not verify ssl certs IFF the installed urllib3 version minor is greater than 24  fixes #467 
Increased the maximum HTTP line length to double the default length in order to ensure super long HTTP lines http are allowed 
urllib3 is now verifying ssl certificates by default.
This is a breaking change from its previous which was to **not verify by default**

Allow pywb to handle urllib3 >= 1.25.x

---

pywb/rewrite/cookie_rewriter.py

A number of websites routinely set cookies with technically invalid characters in the name. For instance, 'ballotbox/respondent_id'`, is set by https://fox13now.com/2017/08/24/federal-appeals-court-upholds-injunction-against-vidangels-streaming-service/. Browsers don't generally object, but python does.
Pywb is prepared for such cookies and [catches the exception](https://github.com/webrecorder/pywb/blob/master/pywb/rewrite/cookie_rewriter.py#L20), but presently prints a stack trace to stdout every time.
This PR switches from `traceback.print_exc()` to `logger.info(e, exc_info=True)` to give pywb users more control over this logging, including the ability to suppress it.
(Contributed as part of our interest in funneling all Pywb/Webrecorder logs through python's logging module, so as to …

CookieError logging

---

pywb/warcserver/index/cdxobject.py

We recently encountered a number of warcs that (due to a separate issue to be discussed over at the warcio repo 🙂), when imported into Webrecorder, caused invalid cdxline byte strings to be passed to `CDXObject.__init__()`
By logging `fields` here, in addition to `len(fields)`, we were more easily able to track down which warcs were causing problems, and were more easily able to identify what the problem was. (FWIW: unencoded spaces in the target url).
While it seems pretty unlikely that anybody else will have the same problem we did, it does seem likely that anybody dealing with invalid cdxlines will benefit from seeing bad data logged here in its entirety.
So! In case you care to add it, here's a PR that adds that little bit of extra logging.
If you don't care to add it, totally feel …

Proposed: More detailed logging of invalid cdxlines.

---

pywb/warcserver/inputrequest.py
pywb/warcserver/test/test_inputreq.py

This is a first pass at resolving #471
The new test intentionally demonstrates that this is a more of a workaround than a real "solution" per se.... what a weird-looking, useless query string... Even though this permits playback to proceed (and restores the behavior of earlier versions of pywb), I wonder if we might be able to do better by base64-encoding it and appending it to __wb_post_data= as in the else clause... but I'm not really qualified to speculate on these topics at this point lol.
Happy to iterate on this / adjust in any way.

Fix #471: failed playback due to encoding issue

---

wombat/src/wombat.js

This PR fixes two issues:
- extractOriginalUrl() now takes into account the abs or rel prefix, if available, in determining the original url. The original url, eg: `http://realoriginal.example.com/` is extracted properly from `http://example.com/1234/http://another.example.com/4567/http://realoriginal.example.com/`
given prefix `http://example.com/1234/http://another.example.com/`.
- Since initHashChange/receive_hash_change() are registered before message event overrides,
check the wrapped message directly via .from_top to determine if it came from top frame.

Wombat Improvements for extractOriginalUrl and hash change

---

docs/manual/configuring.rst

The Docs specify the default value for the warc files path as 'archives' but the default config.yaml file specifies 'archive'
https://github.com/webrecorder/pywb/blob/master/pywb/default_config.yaml#L4

Update configuring.rst to reflect default config.yaml.

---

docker-entrypoint.sh
pywb/apps/frontendapp.py
pywb/apps/rewriterapp.py
pywb/apps/static_handler.py
pywb/rules.yaml
pywb/version.py
pywb/warcserver/test/testutils.py
tests/test_root_coll.py

updated rules for soundcloud to work with latest api changes
misc fixes:
- ensure SCRIPT_NAME is never empty, fixes #466
- static: if ending in '/' look for '/index.html'
- tests: use local httpbin instead of iana.org tests
- docker: switch to $VOLUME_DIR before initing collection
- ensure static_prefix is set correctly after host prefix
- bump version to 2.3.2.dev0

Misc fixes for 2.3.2 release

---

pywb/rewrite/regex_rewriters.py
pywb/rewrite/test/test_regex_rewriters.py

Ensured that the regular expressions for rewriting JavaScript eval us…age do not match when prefixed with ".$"
Angular uses a function `$eval` to perform its magic, more specifically as `this.$eval`.
Rewriting this instance of `eval` is incorrect and with these changes Angular's usage `.$eval` is not rewritten. 
URLs requiring change
- https://webrecorder.io/mirrorsedgefan/mirrorsedge/list/bookmarks/b5/20180401180131/http://www.mirrorsedge.com/intel/the-conglomerate
- https://webrecorder.io/CHArchives/carnegie-hall---performance-history-search-2018/list/all-pages/b2/20180514153214/https://ektpreprod.corp.carnegiehall.org/PerformanceHistorySearch/#

Server side regex rewriting tweak for JavaScript eval

---

CHANGES.rst
pywb/rewrite/html_insert_rewriter.py
pywb/rewrite/test/test_html_insert_rewriter.py
pywb/version.py

Ensure HTMLInsertOnlyRewriter handles pages with no `<head>` tag, insert
head-insert before first tag that is not `<head>` or `<html>`, similar to full
HTMLRewriter
Many pages (eg. new twitter.com) do not include a head tag!

proxy mode HTMLInsertOnlyRewriter:

---

CHANGES.rst
pywb/apps/rewriterapp.py

The domain cookie cache (revampled in 2.3.3) excluded service workers if non-200 response.
It appears that cookie headers should be excluded form cacheing for all sw responses.
This fix fixes login through pywb to Twitter, which uses domain-level cookies and service workers.

Tweak cookie cacheing to exclude service workers

---

CHANGES.rst
pywb/warcserver/http.py
pywb/warcserver/resource/responseloader.py
tests/test_socks.py

Improves the SOCKS proxy handling:
- https urls over SOCKS were sometimes improperly sent using full url, using higher-level adapter to avoid this
- ensure SOCKS proxy uses same cert verification mode as non proxy (currently no checking).
- removed unnecessary monkey patching, as requests/urllib3 now support socks5 without patching.
- also add a way to toggle proxy with env settings SOCKS_DISABLE
- replace lower-level `adapter.get_connection()` with `adapter.proxy_manager_for(self.socks_proxy)` which returns a proxy manager which determines appropriate url to use with socks proxy.
Loading https://check.torproject.org/ over SOCKS resulted in a 500 error, because the proxy was incorrectly sending `GET https://check.torproject.org/` instead of `GET /`.

SOCKS Proxy Improvements

---

pywb/static/query.js

Fixed calendar view dropping query parameters by using encodeURIComponent fixes #510

Fix calendar view dropping query parameter

---

README.rst
docs/code/pywb.manager.rst
docs/code/pywb.rewrite.rst
docs/code/pywb.rst
docs/code/pywb.utils.rst
docs/code/pywb.warcserver.rst
docs/manual/access-control.rst
docs/manual/configuring.rst
docs/manual/ui-customization.rst
pywb/apps/frontendapp.py
pywb/apps/rewriterapp.py
pywb/templates/frame_insert.html
pywb/version.py
pywb/warcserver/http.py
pywb/warcserver/index/fuzzymatcher.py
tests/config_test.yaml
tests/test_auto_colls.py

Ensure user-metadata, available in metadata.yaml files is consistently passed to
UI templates, separate from config information.
Pass metadata, if any, to frame insert and don't mix with config (ukwa/ukwa-pywb#57)
Also add docs about how to configure custom metadata.
Update README for 2.4 release
Issue raised in ukwa/ukwa-pywb#57 about mixing user metadata and config,
question about metadata in frame_insert.html

Docs, custom metadata improvements

---

pywb/static/query.js
pywb/templates/base.html
pywb/templates/query.html

Adjusts bootstrap responsive classes on query page. Now elements stack for small/mobile viewports.
Currently the page does not respond to browser window size.

Tweak query page to be responsive

---

pywb/warcserver/inputrequest.py

Current indexing reads an entire POST request, which can be quite large, and attempts to append to urlkey query.  Now restrict reading POST request to 16384, skip reading the remainder.
Many sites include large logs in POST during regular browsing (eg. instagram).
Indexing can get quite slow if reading the entire POST request, and is unnecessary.
Supersedes #482, truncating POST request at read time.
It is unlikely that such large queries would ever match exactly and only ever match via fuzzy lookup.

Restrict POST query size

---

pywb/warcserver/index/indexsource.py
pywb/warcserver/index/test/test_xmlquery_indexsource.py

Ensures the XML query based lookup index also includes a limit, if any.
Should address issue in ukwa/ukwa-pywb#49

Ensure limit applies to XmlQuery index

---

pywb/warcserver/index/fuzzymatcher.py

even if no groups are captured by the regex
As we discussed on slack.
```
nlevitt 3:12 PM
hey dude, i have a question about the fuzzy match rules
https://github.com/webrecorder/pywb/blob/5f938e68797/pywb/warcserver/index/fuzzymatcher.py#L70 (edited) 
if i’m reading the code right, if a url prefix matches and the regex matches, but there are no matching groups, then the fuzzy match rule does not apply
ikreymer 3:14 PM
hey, yeah, this could probably benefit from additional comments..
nlevitt 3:15 PM
i’m wondering, if the regex matches, why not consider that a match… and if there are no matching groups, then you just don’t have any urlkey: filters
this came up because some of our fuzzy match rules from java wayback have regexes with no capturing group parens
and i didn’t think about this …
```

apply fuzzy match if url prefix and regex match

---

pywb/static/default_banner.js
pywb/version.py
pywb/warcserver/resource/responseloader.py
pywb/warcserver/test/test_handlers.py
tests/test_redirects.py

Misc fixes for pywb 2.4.0-rc5
Fix to previous banner fix #531 to quickly (hopefully addresses issue mentioned in #527)
Fix `cdx+` query: don't use live loading if WARC file/offset are set
Self-Redirects Improvements: filter out www -> www2. redirects as self-redirects if canonicalized to same key.
Attempting to fix ukwa/ukwa-pywb#53 and issue mentioned in #527

Misc Fixes for RC5

---

pywb/apps/wbrequestresponse.py

Try to remove headers with illegal characters. Fixing the following issue arquivo/pwa-technologies#774
Pywb is not able replay records with illegal characters (outside latin1) in the replay headers.
In example above there is a Trademark character on the Server header that breaks the streaming of the response.
This change try to fix those badly formed headers, detecting them and removing them. Its a best enforce approach, in last case the record will fail to load as it was.
arquivo/pwa-technologies#774
After this fix:
I am not sure if this is the best approach, open to do any change needed to make it go upstream.

Try to remove headers with illegal characters.

---

docs/manual/cdxserver_api.rst

Fix documentation.
On CDX Server API the 'fl' params have been replaced with 'fields'.

Fix documentation: replace fl to fields on doc webrecorder/pywb#542

---

docs/manual/configuring.rst

Per the code, the key should use an underscore, not a hyphen. It also seems like the value is parsed as a number instead of a string, which then fails with a type error later, so quote it to force it to be a string.
```
$ pywb
2020-03-10 21:06:33,084: [INFO]: Proxy enabled for collection "web"
Traceback (most recent call last):
File "/tmp/pywb_venv/bin/pywb", line 8, in <module>
sys.exit(wayback())
File "/tmp/pywb_venv/local/lib/python2.7/site-packages/pywb/apps/cli.py", line 20, in wayback
desc='pywb Wayback Machine Server').run()
File "/tmp/pywb_venv/local/lib/python2.7/site-packages/pywb/apps/cli.py", line 89, in __init__
self.application = self.load()
File "/tmp/pywb_venv/local/lib/python2.7/site-packages/pywb/apps/cli.py", line 181, in load
return …
```

docs: fix proxy default timestamp yaml example

---

pywb/warcserver/warcserver.py

If you configure some proxy settings like enable_content_rewrite in config.yaml, when you run wayback --proxy mycollection it does not work.
This is because the entire proxy section is replaced by the extra config (custom_config) generated according to the command line arguments in cli.py.
This fix makes the section values to be replaced, but not the entire section. So the existing values won't be removed.
Another approach would be to add command line arguments for the rest of the available settings  like --proxy-enable-content-rewrite, etc... I don't know which is preferred in this project.

proxy mode: respect settings when started from cli

---

.travis.yml
extra_requirements.txt
pywb/apps/rewriterapp.py
pywb/rewrite/html_insert_rewriter.py
pywb/rewrite/test/test_html_insert_rewriter.py
pywb/utils/loaders.py

In proxy mode, don't inject header for ajax requests. Detect via Sec-Fetch-Mode header,
since not adding custom pywb headers
Fixes proxy mode replay of fulcrum sites, eg. https://www.fulcrum.org/epubs/t722h883s?locale=en#/6/2[Cover1]!/4/4/1:0
Minor fix / CI support for py3.8

proxy mode: don't rewrite xml for ajax requests. Support python 3.8

---

pywb/apps/rewriterapp.py
tests/test_memento.py

Fixes timegate behavior in framed replay mode, so that:
- timegate headers match timegate on content frame, (mp_/), but without memento header
- 404s correctly reported if no match found
This results in actual lookup of the content, which is then discarded, and the top frame html is returned along with the memento headers
Should fix ukwa/ukwa-pywb#58, as well as #547, #549

memento timegate: Fix for timegate in framed replay

---

docs/manual/access-control.rst

In the access control documentation, there exists a link to an external resource. This link is written in markdown (MD) format whereas the document itself it reStructureText (RST). This PR updates the link to use RST-style syntax and the inline formatting used in other pywb documentation (cf. links at the end and a keyword used).
I noticed this issue when reviewing the documentation at https://pywb.readthedocs.io/en/latest/manual/access-control.html . The link there exposed both the URI destination as well as the text to be linked without appropriately encoding the link on render.

Fix link in access-control docs to use RST instead of MD syntax

---

docs/manual/usage.rst

The example in the current docs is incorrect - the section about [Using pywb recorder](https://pywb.readthedocs.io/en/latest/manual/usage.html#using-pywb-recorder) currently reads:
> For example, to record `http://example.com/`, visit `http://localhost:8080/my-web-archive/record/<url>`
This PR simply replaces `<url>` with `http://example.com/`, as (probably) intended by the writers of the documentation. I thus discarded the rest of the PR template as it does not apply to such a small change (I would assume).

docs: Fix incorrect example

---

pywb/indexer/test/test_indexing.py
pywb/warcserver/inputrequest.py
pywb/warcserver/test/test_inputreq.py

Catches `ValueError` on a multipart/form-data mime when "boundary" is missing, and handles it in the same way as an earlier condition for 'application/x-www-form-urlencoded' erroring on `UnicodeDecodeError`.  When I try to run the tests with `python setup.py test`, test_proxy.py tests fail, but this seems unrelated and is the same when I run them on the `master` branch.
Fix for #598 to handle a `ValueError` on a multipart/form-data mime when "boundary" is missing.

Handle Content-Type multipart/form-data without boundary

---

docs/manual/configuring.rst
pywb/warcserver/http.py
pywb/warcserver/warcserver.py
tests/config_test_cert_req.yaml
tests/test_cert_req.py

For Security reasons it may be desirable to reject invalid certificates. This adds configuration
options to configure this.
Fixes: #594

Add support for verifying ssl certificates 

---

pywb/apps/wbrequestresponse.py

Catch TypeError thrown by uWSGI in addition to UnicodeError
The fix for invalid headers merged with webrecorder/pywb#536 seems not to be working with Docker/uWSGI/Python3. Looking at https://github.com/unbit/uwsgi/blob/master/plugins/python/wsgi_headers.c#L140, uWSGI is throwing a TypeError, not a UnicodeError. However, UnicodeError is correct when not using uWSGI (e.g. run with cli.py).
Catching the TypeError solves the replay problem also when running pywb with Docker/uWSGI/Python3.

Catch uWSGI TypeError for invalid headers

---

pywb/static/default_banner.css
pywb/static/default_banner.js

Added prefix/namespace to css class "mobile" (new: "_wb_mobile") in the default files. 
As the banner CSS may get injected, this can lead to conflicts with the replayed site if a "mobile" class is used.

Fix default banner css namespacing

---

pywb/warcserver/index/indexsource.py

Raise the default limit of the number of records returned when querying CDX for the closest records.
At UKWA we're hitting cases where crawl variation means we have e.g. a lot of redirect records and in these cases the 10 record limit is too low.  I can't see any way of configuring this value, so I'm proposing the default is raised.

Default closest_limit to 100 instead of 10

---

pywb/indexer/cdxindexer.py

As mentioned in #608 and explained in: https://stackoverflow.com/a/53023435
it turns out the CDX sorting that pywb uses is less efficient, than the default list sort.
In fact, it appears to be that the current sorting ends up being O(n^2) instead of O(n * log n), which would cause significant perf issues for larger indexes.
This switches to just aggregating all cdx, and sorting at the end.
Sometimes the simpler solution is the correct one!

CDX sorting: Default list sort is more efficient

---

docs/manual/configuring.rst
pywb/apps/frontendapp.py

Deduplication has been available already, but it can't be enabled. This adds the configuration options to be able to use deduplication.

Add configuration options for dedup 

---

docs/manual/configuring.rst
pywb/apps/cli.py
pywb/apps/frontendapp.py
pywb/apps/rewriterapp.py
pywb/recorder/multifilewarcwriter.py
pywb/recorder/redisindexer.py
pywb/recorder/test/test_recorder.py
pywb/warcserver/warcserver.py

Expand/simplify the deduplication functionality added in #597.
- A default redis URL is now used, but is customizable
- When using dedup policy, instant replay is possible to view what has been archived w/o waiting for autoindexing or manual reindexing.
- Updated docs to reflect the latest setup.
Still TODO: add tests for this system, which is already in using by browsertrix-crawler

Dedup Improvments

---

docs/manual/access-control.rst
pywb/warcserver/access_checker.py
pywb/warcserver/warcserver.py

To make the ACL checker work for automatic collections: pass the collection name to the ACL checker, so that the ACL loader is able to expand the template paths (`{coll}/acl/`).

Fix ACL loading for auto collections

---

pywb/warcserver/access_checker.py
pywb/warcserver/test/test_access.py
sample_archive/access/pywb.aclj
sample_archive/access/single-line.aclj

This PR addresses #628.
The key used to search for a ACL rule is the SURT URL followed by `###`, e.g.
```
org,iana)/path/###
```
The exact-match rule in the ACLJ file consists of the SURT URL followed by `###`, a white space, the timestamp and the JSON data:
```
org,iana)/path### - {"access": "allow", "url": "http://www.iana.org/path/"}
```
Because the rule line sorts before (in reverse alphabetical order) the search key, the "search cursor" is then positioned just after the rule line and not before it. Although AccessChecker requests one additional line (`prev_size=1`) before the search position [line 41](https://github.com/webrecorder/pywb/blob/78a9888b4673b33cfa263b5ced684a9c855331d5/pywb/warcserver/access_checker.py#L41), this has no effect in a single-line file because we reach EOF …

AccessChecker: exact-match rules not found in single-line ACLJ file, fixes #628

---

pywb/warcserver/handlers.py

While CDXQuery supports the old query parameter `fl` ([query.py#L88](/webrecorder/pywb/blob/78a9888b4673b33cfa263b5ced684a9c855331d5/pywb/warcserver/index/query.py#L88)), the class IndexHandler does not,
The PR add backward-compatibility support for the query parameter `fl` (in addition to the param `fields`).
The change is part of an effort to upgrade [Common Crawl's CDX server](https://index.commoncrawl.org/) to the recent version of PyWB while ensuring 100% API compatibility (see commoncrawl/cc-index-server#8). Teaching the users a new API and upgrading all clients in the wild seems impossible as there are too many.

IndexHandler: backward-compatibility for `fl` (fields) param

---

pywb/warcserver/handlers.py
tests/test_cdx_server_app.py

Warcserver throws a "TypeError" (message: `'list' object is not callable`) when
- the [output format](https://pywb.readthedocs.io/en/latest/manual/cdxserver_api.html#output), passed via the CDXJ API param `output`, is not supported
- and, as a site condition, the param `fields` requests a list of output fields
The expected behavior is to throw a BadRequestException and report the unsupported output format.

Warcserver / CDXJ API: properly handle unsupported output formats

---

pywb/apps/frontendapp.py
pywb/warcserver/basewarcserver.py

The patch makes FrontendApp forward the HTTP status of the CDX backend, so that clients can handle errors properly.
If the CDX backend fails to process a query, the FrontendApp still responds with HTTP status `200 OK`. The (error) status (eg. "400 Bad request", "404 Not found", etc.) should be passed forward to the client.
A clear HTTP error simplifies the processing of the CDX results in the client. The fix also ensures that the CDXJ API is compatibility with the behavior of the API in PyWB 0.33.2.
One example to reproduce the issue:
- call the CDXJ API with an unsupported output format (`...&output=foo`)
- the FrontendApp responds with HTTP status 200. Only the response body indicates that there was actually an error and shows the reason `{"message": "output=foo not supported"}`
With …

FrontendApp: forward HTTP status of CDX backend

---

pywb/apps/frontendapp.py
pywb/warcserver/handlers.py
tests/test_zipnum_auto_dir.py

WarcServer should handle CDXExceptions and respond with HTTP status "400 Bad Request".
The PR reads the first line of the CDX result early so that the exception is raised and be caught and forwarded as error.
The unit test included in this PR is based on #624 (included in this PR).
- ensures backward-compatibility with the CDXJ server of PyWB 0.33.2
- some CDX clients (eg. [cdx-toolkit](https://pypi.org/project/cdx-toolkit/)) iterate over result pages until an invalid page number is hit and the server responds with "404 Bad Request". If the error is not properly handled and the server responds with status 500, the client tries the same request (with the page number out of range) again and again.
Log output and stacktrace of the error:
```
Traceback (most recent call last):
File …
```

Handle CDXException and respond with HTTP 400 Bad Request

---

pywb/warcserver/index/query.py
pywb/warcserver/index/test/test_zipnum.py
pywb/warcserver/index/zipnum.py

If requests to the CDXJ API include invalid `page` or `pageSize` params the server fails with "HTTP 500 Internal Error". It should fail with "HTTP 400 Bad Request" instead.
Seen with CDX client not properly escaping the value of the url param, eg. `http://example.com/do?pagename=homepage&page=UserAction&id=foo&pageSize=1&output=json`.

WarcServer / CDXJ API: fail with CDXException (Bad Request) if params `page` or `pageSize` are no valid integers

---

pywb/warcserver/warcserver.py

The 'dedup_index_url' configuration option should be inside the
'recorder' section.

Fix dedup_index_url configuration option

---

pywb/warcserver/index/aggregator.py
pywb/warcserver/index/test/test_zipnum.py

Do not apply any filters (param filter, from, to, closest) if counting pages (param showNumPages=true) to avoid that the CDX filter/processing fails if it tries to read keys not present in a page-count result.
Avoid error responses "HTTP 500 Internal Error: 'urlkey'" (also 'url' or 'timestamp') which are not helpful.
Ev., could also argue to turn these into bad request responses. The solution here tries to be backward-compatible to PyWB 0.33.2 where filter params are simply ignored.

Zipnum index: fail if counting pages with filter params

---

pywb/warcserver/index/indexsource.py
pywb/warcserver/index/test/test_xmlquery_indexsource.py

Use the compressed length when it's available in XmlQueryIndexSource.
The field is confusingly misnamed `compressedendoffset` in the XML but [OpenWayback](https://github.com/iipc/openwayback/blob/c7fac11479ee4447a71ee337f91018f7808757a2/wayback-core/src/main/java/org/archive/wayback/resourceindex/cdx/format/CompressedLengthCDXField.java#L33) and consequently [OutbackCDX](https://github.com/nla/outbackcdx/blob/5094be4e12f76d083edc72ba2af2d8150dc5170b/src/outbackcdx/XmlQuery.java#L151) actually use this for the "S" CDX field (compressed length).
Without this field when WARC files are accessed over HTTP pywb will make open byte range requests which results in a lot more data being read from disk than necessary.
CC @anjackson 
N/A

xmlquery: use compressed length when available

---

pywb/warcserver/handlers.py
tests/test_cdx_server_app.py

When the CDXJ API is queried with an unknown `matchType` parameter, the failure is reported as "Internal server error" (HTTP status 500).
The patch fixes the IndexHandler to catch the BadRequestException and report is an error (HTTP status "400 Bad request").

IndexHandler: report BadRequestException as error

---

pywb/apps/frontendapp.py
pywb/recorder/recorderapp.py
pywb/recorder/redisindexer.py
tests/test_record_dedup.py

When using the dedup redis index, also track the number of pending requests in Redis, defaulting to the key `pywb:{coll}:pending`.
This allows automated processes that use pywb for recording to detect when pywb is fully done recording data to WARC and may be exited.
Supports webrecorder/browsertrix-crawler#44

Pending count

---

pywb/warcserver/index/indexsource.py
pywb/warcserver/index/test/test_xmlquery_indexsource.py

Remove a space to change `limit: 100` to `limit:100` in the xmlquery protocol to improve compatibility with OutbackCDX.
OutbackCDX can't handle a space here as it decodes fields by splitting on space. As far as I know `limit:` is an OutbackCDXism so I don't think this would have ever worked properly and I don't think any other server implementation (i.e. OWB) supports it. It doesn't seem to break normal browse access but it does affect pywb's "/cdx" API if the client supplies a limit (reported by @wragge).
Note that OutbackCDX 0.8.0+ supports the `&count=` query string parameter that's used in OWB. I didn't know this existed until recently which is how Outback ended up with its own way of doing this. Maybe it'd be better to switch to that instead in future but I'm not doing that in this …

xmlquery: remove space after the "limit:" query field name

---

docs/manual/access-control.rst
docs/manual/cdxserver_api.rst
docs/manual/usage.rst
pywb/apps/rewriterapp.py
pywb/manager/aclmanager.py
pywb/rewrite/rewriteinputreq.py
pywb/version.py
pywb/warcserver/access_checker.py
pywb/warcserver/handlers.py
pywb/warcserver/warcserver.py
requirements.txt
sample-deploy/pywb-apache.conf
sample-deploy/pywb-nginx.conf
sample_archive/access/pywb.aclj
tests/config_test_access.yaml
tests/test_acl.py
tests/test_acl_manager.py
tests/test_embargo.py

This PR adds an embargo system on top of the access control system, allowing blocking of all URLs based on capture date.
The embargo supports blocking:
- captures before or after specific date
- captures older or newer than a specific time interval (in years, months, weeks and/or days)
When combined with ACL rules, the embargo takes precedence, unless the `allow_ignore_embargo` rule is used.
The PR also adds an optional `user` field to the ACL system, allowing specific matches by user, passed to pywb via the `X-pywb-ACL-user` header.
Version bump to 2.6.0b0
Support for embargo system and custom -user based auth as part of work for: 
https://netpreserve.org/projects/pywb/
Docs: Initial pass on updated docs for Embargo + ACL system.

Access Control Improvements: Embargo + ACL User Support

---

CHANGES.rst
babel.ini
config.yaml
docs/index.rst
docs/manual/localization.rst
extra_requirements.txt
pywb/apps/rewriterapp.py
pywb/manager/locmanager.py
pywb/manager/manager.py
pywb/rewrite/templateview.py
pywb/static/default_banner.js
pywb/templates/base.html
pywb/templates/error.html
pywb/templates/index.html
pywb/templates/not_found.html
pywb/templates/search.html

Improved support for localization via `py-babel`
Add `wb-manager i18n` commands for facilitating creation of localized string tables.
Ensure language switch header available on all default templates
Ensure existing strings marked as localizable text.

Localization Support

---

docs/manual/access-control.rst
docs/manual/localization.rst

Fixes some typos in the docs about localization and access control.
While reading the documentation, I noticed some typos and thus am suggesting fixes.

Fix typos in localization and access-control docs

---

docs/manual/cdxserver_api.rst

The CDXJ Server API documentation is improved by
- replacing the outdated `/coll-cdx` API endpoint by the default API endpoint `/<coll>/cdx`
- if clear from preceding context, the API endpoint is removed from the examples which now include only the query params: `?url=...&param1=...`

Improve docs about CDXJ Server API endpoint

---

docs/manual/rewriter.rst

1. Missing a line break.
2. Thoese Python modules are called [`pywb.rewrite.*`](https://github.com/webrecorder/pywb/blob/81308780ecc17a393b684d320d80dada309b4694/pywb/rewrite/default_rewriter.py), not `pywb.rewriter`

fix errors in docs/manual/rewriter.rst

---

pywb/static/search.js

Searching for URL's with semicolons fails because the url search paramater is not encoded in the request from the frontend to the backend. The backend receives the full URL but in the request to the CDXJ server the request is cutoff at (and including) the first semicolon.
#656 
- [ X] Bug fix (non-breaking change which fixes an issue)

Encode url search parameter when performing query

---

docs/manual/owb-to-pywb-deploy.rst
docs/manual/usage.rst

Fixes links in the docs that pointed to a now non-existent branch.
To fix broken links.
documentation

docs: fix broken links

---

pywb/indexer/cdxindexer.py

Modifies the examples given in the help text of the `cdx-indexer` script.
Currently the examples given at the end of the `cdx-indexer` script's help text do not work as stated because the intended output locations are being interpreted as input locations. Here is the text at the end of the help given with `cdx-indexer -h`:
```
Some examples:
* Create "example.cdx" index from example.warc.gz
cdxindexer.py ./cdx/example.cdx ./warcs/example.warc.gz
* Create "combined.cdx", a combined, sorted index of all warcs in ./warcs/
cdxindexer.py --sort combined.cdx ./warcs/
* Create a sorted cdx per file in ./cdx/ for each archive file in ./warcs/
cdxindexer.py --sort ./cdx/ ./warcs/
```
Here's output of running the first example, though the two paths do exist:
```
$ ls -l ./cdx …
```

Modify examples in cdx-indexer help text to do as stated

---

docs/manual/new-vue-ui.rst
docs/manual/template-guide.rst
docs/manual/ui-guide.rst
pywb/apps/frontendapp.py

This is mostly typo fixes on the new ui and template docs.
There is one change to code for making the `ui` template variable available in the collection page template to make the variables consistent with the [documentation](https://pywb.readthedocs.io/en/docs/manual/template-guide.html#collection-page-template). Currently the `ui` config settings are otherwise only available in that template as `{{ coll_config.ui }}`.

New UI corrections

---

pywb/utils/test/test_binsearch.py
pywb/warcserver/resource/responseloader.py
pywb/warcserver/resource/test/test_pathresolvers.py

There are small typos in:
- pywb/utils/test/test_binsearch.py
- pywb/warcserver/resource/responseloader.py
- pywb/warcserver/resource/test/test_pathresolvers.py
Fixes:
- Should read `length` rather than `lenghth`.
- Should read `equals` rather than `eqauls`.
- Should read `assume` rather than `asume`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

pywb/apps/rewriterapp.py
pywb/warcserver/index/test/test_indexsource.py
tests/test_redirect_classic.py

When 'redirect_to_exact' is enabled, the top-frame expects a redirect for top-frame.
However, when running in live mode, do not expect redirect for top-frame, render live top-frame same as before
Tests: ensure top-frame loads correctly for live mode with redirect_to_exact enabled
Tests: fix webneact index tests

live route fix:

---

CHANGES.rst
pywb/version.py
requirements.txt

Need to add dependency for 'markupsafe<2.1.0' as latest version breaks pywb
Bump to 2.6.5

Markupsafe fix

---

CHANGES.rst
Dockerfile
pywb/rewrite/default_rewriter.py
pywb/rewrite/test/test_content_rewriter.py
pywb/utils/test/test_loaders.py
pywb/version.py
requirements.txt
tests/test_integration.py

Fix user-agent detection to not user werkzeug (due to obsolete package), and use ua_parser
- werkzeug user-agent is no longer supported (#704) and returns incorrect results on browsers >100
- use ua_parser to detect browser version, use old-style location rewriting only for detected older browsers, default to newer rewriting by default #707

User-Agent Detection Fix + New-Style rewriting on by default + Dependency Update (2.6.6)

---

CHANGES.rst
pywb/warcserver/inputrequest.py

Fix for #709
Updates post-to-get JSON conversion used by internal cdx-indexer. This insures the cdx/cdxj generated by pywb's internal cdx-indexer match the cdxj-indexer

Post query json parse fix

---

requirements.txt

Upgrade `webassets` dependency to use version 2.0
Version 2.0 updates usage of yaml to use `safe_load` instead of `load` [which was deprecated](https://github.com/miracle2k/webassets/pull/525) and now throws an error when a loader isn't also supplied:
```shell
Traceback (most recent call last):
File "/code/./webrecorder/main.py", line 9, in <module>
application = MainController().app
File "/code/./webrecorder/maincontroller.py", line 110, in __init__
jinja_env = self.init_jinja_env(config)
File "/code/./webrecorder/maincontroller.py", line 200, in init_jinja_env
jinja_env_wrapper = JinjaEnv(assets_path=assets_path,
File "/usr/local/lib/python3.8/site-packages/pywb-2.6.7-py3.8.egg/pywb/rewrite/templateview.py", line 98, in __init__
assets_env = assets_loader.load_environment()
File …
```

Upgrade webassets to v2.0

---

pywb/rewrite/html_rewriter.py
pywb/rewrite/test/test_html_rewriter.py

When the image attribute **[srcset](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images)** value contains an unsupported character(https://www.rfc-editor.org/rfc/rfc3986#section-2) then the url will be encoded. In this case the value contains a space and the image intrinsic width which will cause a broken image after encoding.
This resolves the problem with encoding image url excluding the intrinsic width. 
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] I have added or updated tests to cover my changes.
- [ x] All new and existing tests passed.

Encoding image 'srcset'  value including the intrinsic width

---

docs/manual/usage.rst

This PR makes two modifications to the example Docker commands in pywb's usage documentation:
* Adding the repository name to the example `wayback` command
* Updating the example `wb-manager add` command to reflect the path to the WARC file inside the Docker volume rather than on the Docker host
These fixes will make it easier for users to run Dockerized pywb without needing to debug why the provided sample commands aren't working.

Fix example Docker commands in usage docs

---

pywb/templates/search.html

This PR adds jinja2 `safe` filters to metadata values and an `{% autoescape false %}` block to the collection title in the search template to prevent HTML markup in collection metadata from being escaped.
Connected to https://github.com/webrecorder/pywb/issues/727
This fixes a regression in more recent versions of pywb which was reported by users.
(copied from linked issue)

Prevent jinja2 from escaping HTML markup in collection metadata

---

sample-deploy/pywb-nginx.conf

I was playing back a YouTube video and noticed that the playback worked
fine with using uwsgi/pywb directly but failed when using nginx. I think
a very long HTTP Link header was causing nginx to hang up. I increased
the uwsgi_buffer_size to 8k and the problem went away. Maybe this will
save someone else some time if it is increased?
https://nginx.org/en/docs/http/ngx_http_uwsgi_module.html#uwsgi_buffer_size

Increase uwsgi_buffer_size for nginx config

---

pywb/templates/search.html

Add the `{% trans %}`/`{% endtrans %}` tags for the `placeholder` text of the `filter-expression` field on the `search.html` page.
Needed in order for translators to be able to translate it to other languages.
The `tests/test_auto_colls.py::TestManagedColls::test_add_static` test is failing with and without this change. The other 807 tests passed.

Add missing translation for the filter-epression field placeholder

---

pywb/static/search.js
pywb/templates/search.html

Add an id tag to the advanced search options button and bind a lambda function to clicking on it in order to activate field validation when expanding the advanced options.
Having to click Search with an empty URL in order to get instructions about what format the from and to timestamps should be is not obvious. If you have already entered a URL there's no way to get feedback on entered values short of removing the URL and clicking Search.
It would make more sense to enable field validation as soon as the advanced options are expanded. (I'm guessing it is not enabled from start to avoid getting an error message on every new search.)
Current behavior: 
Expected behavior: 
The `tests/test_auto_colls.py::TestManagedColls::test_add_static` test fails with or without this change but the other …

Activate field validation when expanding the advanced options

---

pywb/utils/loaders.py
pywb/utils/test/test_loaders.py

- enables the S3 loader to use [boto3 built-in methods to configure AWS credentials](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#configuring-credentials)
- re-enables the S3 loader tests reading from s3://commoncrawl/ to test authenticated S3 access
So far, authenticated reads from S3 were only possible by explicitly passing AWS credentials to the S3Loader. Boto3 supports more multiple methods to [configure/provide credentials](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#configuring-credentials).
The priority when configuring the S3 client is now:
1. use the credentials passed into the S3Loader
2. (newly introduced) try other boto3 built-in methods (environment variables, configuration files, IAM roles)
3. try …

S3 loader to use boto3 built-in credential configuration

---

README.rst

Describe installation using `pip` in `README.rst`.
The current section on installation describes how to clone `pywb` and build/install it locally. 
This is complicated, it is enough to simply `pip install pywb`.

describing installation using pip

---

docs/manual/usage.rst

Hi there, folks!
This updates the [_Docker Deployment_ section](https://pywb.readthedocs.io/en/latest/manual/usage.html#docker-deployment) to include the image organisation/name to the sample commands

Add missing org/image to docker run commands

---

pywb/static/css/base.css
pywb/templates/error.html

Currently error messages display on a single line that can be difficult to scroll. This updates the CSS slightly to allow the message to spread over multiple lines if needed.
To make it (a little bit) easier to read error messages.

Format error messages

---

pywb/warcserver/index/cdxobject.py

If a CDX entry has a status that is an integer instead of a string (which is what ArchiveWeb.page currently generates) then pywb will blow up during replay:
```
Traceback (most recent call last):
File "/Users/edsummers/Projects/pywb/pywb/warcserver/basewarcserver.py", line 77, in __call__
result = endpoint(environ, **args)
File "/Users/edsummers/Projects/pywb/pywb/warcserver/basewarcserver.py", line 46, in post_fullrequest
return handler(params)
File "/Users/edsummers/Projects/pywb/pywb/warcserver/handlers.py", line 160, in __call__
out_headers, resp = loader(cdx, params)
File "/Users/edsummers/Projects/pywb/pywb/warcserver/resource/responseloader.py", line 37, in __call__
entry = self.load_resource(cdx, params)
File "/Users/edsummers/Projects/pywb/pywb/warcserver/resource/responseloader.p …
```

Ensure CDX status is a string

---

pywb/static/default_banner.js

* Puts banner in header and nav landmark regions
* Adds landmark role of banner to header
The SiteImprove automated accessibility checker flags the replay banner for not following [ARIA Authoring Practices](https://www.w3.org/WAI/ARIA/apg/practices/landmark-regions/), specifically concerning landmark regions.  These changes are intended to improve site navigation by screen readers.

Improve replay banner's accessibility

---

pywb/version.py
pywb/warcserver/resource/responseloader.py
tests/test_integration.py
tests/test_redirect_revisits.py

Revisit records may contain HTTP headers, or they may contain no headers. If they do contain headers, the replay should use the HTTP headers from the revisit record, and they payload from the original record referenced by the revisit.
Unfortunately, this was not working (possibly ever?) as expected!
It appears that pywb was always using the HTTP headers from the original record.
Generally, this is fine, except in the case where the revisit record is of a redirect, and the HTTP headers have changed between the revisit and the original (while the payload is the same, and generally ignored).
This fixes an issue originally found in sul-dlss/was-pywb#64
Added test case which I believe replicates this issue.
cc: @edsu

Revisit headers load fix

---

pywb/static/query.js
pywb/templates/query.html

A few strings on the search results pages were hard coded an not enclosed with the translation function which gave the page a half translated impression.
* add the remaining strings to the `text` dict in `query.html`
* `for matching` / `captures of`
* `by`
* `Mime Type`
* `HTTP Status`
* replace the occurrences of those strings with the corresponding dict element in `query.js`
* tidy up the usage of bold in `query.js` for consistency
* use the `tsToDate()` function also for the timestamps for search results without matchType
* use the `document.documentElement.lang` parameter to decide how to localize the timestamps in `query.js`
The last item means that if the user has chosen a language for the page the timestamps will be formatted accordingly; otherwise the locale of the browser will …

Enable translation for the remaining strings on the search results page

---

pywb/apps/wbrequestresponse.py

Add `Cross-Origin-Resource-Policy: cross-origin` header to static resources served in proxy mode, to avoid errors in later versions of Chrome.

proxy: add COEP header for proxy mode to avoid errors

---

README.rst
pywb/manager/locmanager.py
pywb/manager/manager.py
setup.py
test_requirements.txt
tests/test_locales.py
tox.ini

- Since `python setup.py test` is now obsolete, recommend running tests locally with tox
- move test requirements to test_requirements.txt to share between setup.py and tox.ini
- Update README to recommend using 'tox --current-env' for running tests locally,
- add py3.10 to tox environments
- ensure test run without i18n extras installed
- replaces #741

tests run improvements: update from python setup.py test -> tox 

---

pywb/rewrite/content_rewriter.py
pywb/rewrite/test/test_content_rewriter.py

Fix edge-case rewriting where HTML page starts with BOM followed by `<!DOCTYPE html>`.
Previously, was not detect as HTML.
Add new test for this.
Fixes #756

rewrite: detect edge-case where html starts with bom followed 

---

pywb/rewrite/rewrite_dash.py
pywb/rules.yaml

Improve twitter rewrite to also use mp4 for videos in twitter embed
Partial fix to embedded tweets, as described in webrecorder/browsertrix-crawler#160

rewriting fix: twitter video in embedded tweets

---

pywb/rewrite/content_rewriter.py
pywb/rewrite/default_rewriter.py
tests/test_integration.py

The `ir_` modifier serves content w/o rewriting, similar to `id_`, but does rewrite Location headers such that they can be followed, especially when loading in the browser.
To support loading resources w/o rewriting, while still following redirects.

Add ir_ modifier

---

.github/workflows/release.yaml

Adds arm64 to the Docker Hub Github Action. Has been tested at [communityfirst/pywb](https://hub.docker.com/r/communityfirst/pywb).
We need to run this on arm64 devices: Pi 4s

Add arm64 platform support

---

pywb/static/query.js
pywb/static/search.js
pywb/templates/query.html
pywb/templates/search.html

Add some more strings for translation by moving them from javascript files to the corresponding HTML templates
Also make pressing enter in the filtering expression field less surprising by adding a new filter instead of submitting the search without the filter being created. If no new filter is being created fall back to the previous behavior of submitting the form.
All strings should be translatable to avoid annoying language mix ups. This PR fixes the remaining strings in `query.js` and `search.js`.
The query page where `Filtering by` and `Contains` et al. were previously not translatable:

Make filter expressions translatable

---

pywb/indexer/cdxindexer.py

stop auto indexing from crashing when warc records can't be indexed
catch the exception, log the error
autoindeling continues
- [X ] Bug fix (non-breaking change which fixes an issue)

issue_792 catch warcio exception

---

pywb/manager/manager.py

Show an error when adding a warc file that has the same filename as an existing file in the collection and do not overwrite the existing file.
See #795

[#795] Show error when adding duplicate warc file

---

pywb/static/query.js
pywb/static/search.js
pywb/templates/instructions.html
pywb/templates/query.html
pywb/templates/search.html

Most people who encounters the Pywb search page for the first time get thoroughly confused. And even after using the search page for a while it's inner workings remain a mystery to many users. This change tries to remedy that.
* Change the "Advanced Search Options" label to just "Search Options", as "advanced" is misleading and discourages using these options.
* Skip the initial field validation as the only field that now can be invalid is an empty URL field and the green check marks clutter the UI unnecessarily. If trying to search without a URL the validation will still trigger.
* Add a "Default" match type to clarify that that options actually exists
* Change the timestamp inputs to a combination of a date and a time field to remove the possibility for inputing invalid timestamps. Keep …

Make search page more intuitive

---

CHANGES.rst
pywb/static/search.js
pywb/templates/search.html

This PR modifies the search template's button colors for readability/UX purposes, and replaces the "Clear Options" button with a "Reset" button that clears both the search options and the URL search box.
Before:
After:

Modify search template buttons

---

pywb/apps/frontendapp.py

Before a language is selected in a Pywb session it's expected that the `default_locale` from the config-file would be used. This works most of the time but not for eg. formatting dates on the query.html page where instead the `en` locale is used.
Let the FrontEndApp `__init__` method set a `default_locale` attribute as defined in the config file and use that as the default for incoming requests.
See issue #804.
See issue #804.

[#804] Use default_locale when lang not set in the request

---

pywb/rules.yaml
pywb/warcserver/index/fuzzymatcher.py
pywb/warcserver/index/test/test_fuzzymatcher.py

substituion functionality already exists on a global level for matched rules but this causes issues when rule sets conflict in the desired outcome. This change enables setting regex substitution at the rule level to avoid these conflicts.
The only change to existing functionality is related to the `find_all` parameter moving to be an options in the `re_type` parameter. I've marked this down as a potentially breaking change as it may impact end users custom rule set, the default rules in the `rules.yaml` have been updated.
We have experienced a number of issue that the rules.yaml functionality would resolve but due to substitutions being linked to the more global `url_normalize` functionality we couldn't make use of it fully.
An example issue this would resolve is #694. For this example a …

feat: regex substitution on surt rules match

---

pywb/rules.yaml

Forces facebook and instagram to not use batching of graphql queries, allowing for more consistent capture and replay.

rules: add 'debugNoBatch' rewrite for fb and insta

---

pywb/apps/frontendapp.py
sample_archive/access/pywb.aclj
tests/test_acl.py
tests/test_embargo.py

Find custom http headers in the incoming request and forward them to the cdx-request. A custom header in this context is one prefixed with `HTML_X_`.
The difference between the `block` and `exclude` actions in the ACL is that the former should allow access to the index but not the data whereas the latter should block both index and data access.
See issue [#715] which is about `allow_ignore_embargo` not allowing access to the index when specified with a specific `user`. On investigation the issue also affected other use cases. The change set includes new tests for theses cases.

[#715] Forward custom headers for cdx queries

---

tox.ini

This enables us to skip youtube-dl tests in GitHub Actions by ensuring that the "CI" env var is passed to tox.
Test `test_live_video_loader` is failing in CI when it should be skipped.
See: https://github.com/webrecorder/pywb/actions/runs/4290394517/jobs/7509706519#step:5:914

Pass env vars to tox

---

pywb/templates/error.html

Sets the "Pywb Error" string in the `<h2>` heading as translatable in the error.html template.
- The string "Pywb Error" isn't translatable [in this line](https://github.com/webrecorder/pywb/blob/main/pywb/templates/error.html#L6).
- Fixes #867 
The "Pywb Error" isn't translated, but this pull request fixes that.
I have no idea how to run the tests, but hopefully just making a string translatable shouldn't break anything.

Sets "Pywb Error" string as translatable in error template

---

pywb/rewrite/templateview.py

If the language code was missing in the URI, switch_locale(locale) didn't add it (it worked fine if it was present). That means that it produced the same URL for all locales, each missing the language code in the URL.
I added an additional check that checks if the language is set in the URI, and it is changed only in that case. Otherwise if it was missing, it was producing a URL that doesn't contain it - but now it does add the launguage code to the URL if it was missing.
Fixes #870
Notice the current URL for a collection named "test" (not containing any language code in the URL). I hovered the mouse over the link to change the locale to "hr" (top right), and the URL that is in that link is shown on bottom left - it doesn't contain "hr". Same happens when I hover over "en".
I don't know …

Fixes switch_locale not adding locale if missing from URL

---

pywb/apps/frontendapp.py

If the default_locale was set in config.yaml and the URL path didn't contain a language code, it was behaving as if there was a language code in the URL. In that case, it was moving part of the PATH_INFO to SCRIPT_NAME, but as there wasn't any language code in the URL path, it moved something else. This fixes that.
I noticed this bug when the search results (by domain) didn't show any results, in the condition described above.
This fixes #872
I marked it as bug fix, instead of a breaking change, but I'm not 100% sure.
I don't know how to run tests.

Fixes environ paths when default_locale set

---

pywb/rewrite/templateview.py

If default_locale was set, and a web page was visited that doesn't have a langauge code in the path in the URL, the URL path parts returned by get_locale_prefixes() was wrong (e.g. /hrst/ instead of /hr/test/).
I added checks that check if the collection part starts with the current locale or app_prefix before removing them.
I noticed the links for switching locales were wrong in the above described case.
No idea how to test.

Fixes get_locale_prefixes() wrong paths

---

pywb/manager/manager.py
tests/test_manager.py

Ensure that collection index is sorted when adding wacz archives to the collection.
CDXJ indices must be sorted for the binary search algorithm to work. When adding wacz archives and merging there indices with the collection index, the wacz index was just appended to the end of the collection index and the collection index wasn't sorted anymore.

Sort index when adding wacz archives

---

docs/manual/access-control.rst
pywb/warcserver/access_checker.py
sample_archive/access/allow_all.aclj
tests/config_test_access.yaml
tests/test_acl.py

Fixes #881
This PR adds the option to use `*,` as a SURT in ACLJ files to match any URL. This builds off of the existing ability to do this per-TLD, e.g. `com,`.
The PR also adds a passing test for the use case described in the issue (overriding `default_access: block` to all URLs for a specific user), and documents the new option.
This allows administrators to give access to all resources to specific (e.g. staff) users.

Allow ACLJs to use *, SURT wildcard to match all URLs

---

docs/manual/usage.rst

Fixes #898 
Updates the Usage documentation on creating web archives to:
- Drop mention of Webrecorder.io
- Add ArchiveWeb.page
- Add Browsertrix and Browsertrix Crawler
Naming a service that no longer exists under that name and shares our brand identity is probably confusing to users! So let's fix that.

Update usage docs section on creating web archives

---

pywb/manager/manager.py
tests/test_manager.py

Instead of not copying a WARC to the archive directory in case of a filename conflict, this PR instead modifies it to add the WARC with `{original_name}-{dupe index}{extension}` - i.e. `example.warc.gz` would be renamed to `example-1.warc.gz`, then `example-2.warc.gz`, and so on, until a filename that doesn't exist in the archive directory is found.
Should make for a more user-friendly experience of adding archives via `wb-manager add`.

Handle WARC filename conflicts with wb-manager add

---

requirements.txt

It looks like `poetry install` will install the latest version of redis (v5.0.4) instead of what pip installs (v2.10.6). Unfortunately this means that the old version of fakeredis that is pinned in the requirements.txt will not work properly.
Fixes #903
To be able to run pywb using a poetry virtual environment.

Pin redis for fakeredis

---

pywb/warcserver/inputrequest.py
pywb/warcserver/test/test_inputreq.py

Fixes #859 
Modifies the output of POST canonicalization query strings in pywb to use native JSON values for booleans, numbers, and null, rather than a string representation of their Python values.
This commit also adds a more complicated JSON test case that is also in warcio.js to ensure parity.
We now handle numbers like JavaScript's Number.prototype.toString() by dropping decimal from floats if they represent whole number, to ensure consistency between pywb and warcio.js.
This is part of a cross-repo effort to standardize how POST canonicalization works in Webrecorder tools, and document this in a Webrecorder specfiication.
Seems to be working well with fuzzy matching on replay, but could use some additional testing.
- [] My change requires a change to the documentation

Use native JSON values in query string for POST canonicalization

---

Dockerfile
docs/manual/usage.rst
uwsgi.ini

By introducing the UWSGI_MOUNT environment variable in the default `uwsgi.ini` it is not possible to configure the uWSGI mount with an environment variable on the OCI/docker image.
Previously it required to mount a `uwsgi.ini` file for this configuration which is not handy in all setups.
Just setting the argument `--mount` on the command did not work as it collides with the `wsgi` setting in the default `uwsgi.ini`.

Allow to configure uWSGI mount via environment variable

---

tests/test_record_replay.py

Comments out a test in py3.9 which sometimes causes CI to freeze.

Fix py3.9 CI

---

pywb/static/loadWabac.js
pywb/version.py
setup.py

Fixes #937 
Use existing prefix for wabac.js `archivePrefix` instead of recomputing, ensures passthrough handles mount prefix.
Update wabac.js to 2.22.15
bump to 2.9.0b1

simplify: use existing prefix as archivePrefix, fixes #937

---

pywb/warcserver/access_checker.py

Fixes regression introduced in commit 6ae3de9
This fixes a regression introduced in commit https://github.com/webrecorder/pywb/commit/6ae3de946843bb8cc2665af79e06771f02d06686 which resulted from comparing timezone-aware and naive datetimes.
The solution is to make sure the datetime returned by `timestamp_to_datetime` is timezone-aware, using the flag in the warcio function for that purpose.
This is part of removing the deprecated `datetime.utcnow()`, which is removed in recent Python versions.

Use tz-aware datetimes for embargo checks

---

pywb/warcserver/handlers.py
pywb/warcserver/resource/responseloader.py
pywb/warcserver/warcserver.py

The fix is to be more concretely differentiate between these two configurations:
```
remote: cdx+https://remote-archive.example.com/web/cdx
local_coll:
index_paths: cdx+http://outbackcdx:8080/coll
archive_paths: /path/to/mywarcs/
```
The former is for proxying via remote CDX while the latter is the [recommend config for OutbackCDX](https://pywb.readthedocs.io/en/latest/manual/outbackcdx.html#configure-pywb-with-outbackcdx) 
These supersedes the fix proposed in #917 by adding a conditional to check which configuration is used
(remote cdx + local loading or remote cdx + remote liveweb loading) by checking if `archive_paths` was provided,
as is needed for usage with OutbackCDX
The skipping of the livewebloader
is needed to be able to retry the lookup path again for revisit records, while of …

Better fix for #865 / differentiate between remote cdx + local WARCs and remote cdx + liveweb loader
